select 'Number of double breaker having relay settings Info from ASPEN in SI service' as category, count(*) from(
SELECT DISTINCT br.funclocid,EQ.EQUIPMENT,Eq.Description,BR.MRID,BR.FUNCLOCDESC,BR.FUNCLOCID,Br.Gcm_Substation_Id,Aspen.*

FROM TCGACDS.GCM_SCIM_BREAKER BR JOIN TCGACDS.GCM_SCIM_SUBSTATION SUB 

ON Sub.Gcm_Substation_Id=Br.Gcm_Substation_Id AND BR.GCM_JOBID = SUB.GCM_JOBID

JOIN TCGACDS.Ods010_Sap_Floc FL

ON (FL.FLOC_ID = SUBSTR(BR.FUNCLOCID,0,13) || 'PD' || SUBSTR(BR.FUNCLOCID,16)) or (FL.FLOC_ID = SUBSTR(BR.FUNCLOCID,0,13) || 'PD')

JOIN TCGACDS.Ods011_Sap_Equip EQ ON Eq.Functional_Location=Fl.Floc_Id

JOIN TCGACDS.ODS013_EQUIP_CHARS CH ON Ch.Equip_Id=Eq.Equipment

JOIN TCGACDS.GCM_ASPEN_RELAY_SETTINGS ASPEN

ON ASPEN.OD43=CH.CHAR_VALUE AND ASPEN.SUBSTATION=SUB.NAME

WHERE ASPEN.EQUIPMENT_TYPE In ('LINE','BUS TIE','CAPACITOR','TRANSFORMER','BUS PARALLEL BREAKER')

AND BR.GCM_JOBID=(SELECT JOBID FROM TCGACDS.GCM_PROCESS_STATUS WHERE ACTIVEJOBID='Y')

AND Ch.Char_Name='E_OD43_NUMBER'

AND EQ.OBJECT_TYPE IN ('ES_R_EM','ES_R_M','ES_R_SS') AND EQ.SYSTEM_STATUS NOT LIKE '%INAC%' AND EQ.SYSTEM_STATUS NOT LIKE '%DLFL%'

AND BR.FUNCLOCID LIKE '%-%N'

UNION



SELECT DISTINCT br.funclocid,EQ.EQUIPMENT,Eq.Description,BR.MRID,BR.FUNCLOCDESC,BR.FUNCLOCID,Br.Gcm_Substation_Id,Aspen.*

FROM TCGACDS.GCM_SCIM_BREAKER BR JOIN TCGACDS.GCM_SCIM_SUBSTATION SUB 

ON Sub.Gcm_Substation_Id=Br.Gcm_Substation_Id AND BR.GCM_JOBID = SUB.GCM_JOBID

JOIN TCGACDS.Ods010_Sap_Floc FL

ON (FL.FLOC_ID = SUBSTR(BR.FUNCLOCID,0,13) || 'PD' || SUBSTR(BR.FUNCLOCID,16)) or (FL.FLOC_ID = SUBSTR(BR.FUNCLOCID,0,13) || 'PD')

JOIN TCGACDS.Ods011_Sap_Equip EQ ON Eq.Functional_Location=Fl.Floc_Id

JOIN TCGACDS.ODS013_EQUIP_CHARS CH ON Ch.Equip_Id=Eq.Equipment

JOIN TCGACDS.GCM_ASPEN_RELAY_SETTINGS ASPEN

ON ASPEN.OD43=CH.CHAR_VALUE AND ASPEN.SUBSTATION=SUB.NAME

WHERE ASPEN.EQUIPMENT_TYPE In ('LINE','BUS TIE','CAPACITOR','TRANSFORMER','BUS PARALLEL BREAKER')

AND BR.GCM_JOBID=(SELECT JOBID FROM TCGACDS.GCM_PROCESS_STATUS WHERE ACTIVEJOBID='Y')

AND Ch.Char_Name='E_OD43_NUMBER'

AND EQ.OBJECT_TYPE IN ('ES_R_EM','ES_R_M','ES_R_SS') AND EQ.SYSTEM_STATUS NOT LIKE '%INAC%' AND EQ.SYSTEM_STATUS NOT LIKE '%DLFL%'

AND BR.FUNCLOCID LIKE '%-%S')

union
select 'Number of ring bus breaker having relay settings Info from ASPEN in SI service' as category, count(*) from(

SELECT DISTINCT floc.floc_id,ASPEN.SUBSTATION , ASPEN.OD43, SAP.EQUIPMENT, SAP.DESCRIPTION, ASPEN.PROTECTION_TYPE, ASPEN.RELAYID,
 
ASPEN.POSITION,ASPEN.OD43_STATUS, ASPEN.DATE_DIGITIZED, ASPEN.DATE_UPLOADED, BR.MRID BREAKER_ID, BR.FUNCLOCID, BR.GCM_SUBSTATION_ID, SUB.NAME
 
FROM TCGACDS.GCM_ASPEN_RELAY_SETTINGS ASPEN JOIN TCGACDS.ODS013_EQUIP_CHARS EQUIP ON EQUIP.CHAR_VALUE=ASPEN.OD43
 
JOIN TCGACDS.ODS011_SAP_EQUIP SAP ON EQUIP.EQUIP_ID=SAP.EQUIPMENT
 
JOIN TCGACDS.ODS010_SAP_FLOC FLOC ON FLOC.FLOC_ID=SAP.FUNCTIONAL_LOCATION
 
JOIN  TCGACDS.GCM_SCIM_SUBSTATION SUB ON SUB.NAME=ASPEN.SUBSTATION
 
JOIN TCGACDS.GCM_SCIM_BREAKER BR ON BR.GCM_SUBSTATION_ID = SUB.MRID
 
WHERE EQUIP.CHAR_NAME='E_OD43_NUMBER' AND SAP.OBJECT_TYPE IN ('ES_R_EM','ES_R_M','ES_R_SS') AND SAP.SYSTEM_STATUS NOT LIKE '%INAC%' AND SAP.SYSTEM_STATUS NOT LIKE '%DLFL%'    
 
AND ASPEN.EQUIPMENT_TYPE IN ('LINE', 'TRANSFORMER', 'BUS TIE', 'CAPACITOR', 'BUS PARALLEL BREAKER')
 
AND SUB.GCM_JOBID= (SELECT JOBID FROM TCGACDS.GCM_PROCESS_STATUS WHERE ACTIVEJOBID='Y')
 
AND BR.GCM_JOBID = SUB.GCM_JOBID
 
AND (FLOC.FLOC_ID LIKE SUBSTR(BR.FUNCLOCID,0,13) || 'PD-%' AND (SUBSTR(BR.FUNCLOCID, 17)=SUBSTR(FLOC.FLOC_ID, 17, INSTR(FLOC.FLOC_ID, '&')-17)
 
OR SUBSTR(BR.FUNCLOCID, 17)=SUBSTR(FLOC.FLOC_ID, INSTR(FLOC.FLOC_ID, '&')+1))))
 
 
 