SET LINESIZE 200
SET FEEDBACK OFF
--column category heading "Category" Format a51
--column COUNT heading "COUNT" Format a9
--column Comments heading "Comment" Format a10



select '1.0 Number of Recloser objects from GESW' as category, count(DISTINCT M3I_OBJECT_ID) as COUNT, 'Info' as Comments  from TCGACDS.AUTOMATIC_RECLOSER_LOCATION where Circuit_Name1 is not null or Circuit_Name2 is not null

UNION

select '1.1 No.of Recloser objects in GCM connectivity' as category, count(DISTINCT M3I_OBJECT_ID) as COUNT, 'Info' as Comments  from TCGACDS.GCM_CONN_DATA_STORE where M3I_ATTRIBUTE_EQUIP_TYPE='AUTOMATIC_RECLOSER_LOCATION'

UNION

select '1.2 Number of Recloser Objects that should have PE Info from ASPEN' as category, count(DISTINCT AR.M3I_OBJECT_ID)  as COUNT, 'Info' as Comments from TCGACDS.AUTOMATIC_RECLOSER_LOCATION AR
INNER JOIN
(SELECT DISTINCT CIRCUIT,LTRIM(EQUIPMENT_NUMBER,'0') as EQUIPMENT_NUMBER,KEY_GROUPNAME 
from TCGACDS.GCM_ASPEN_RELAY_SETTINGS where EQUIPMENT_TYPE in ('AR')) ASPEN
ON LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(AR.LINE_DEVICE_NO,'RAR'),'RSR'),'RIS'),'AR'),'0')=ASPEN.EQUIPMENT_NUMBER
and (Ar.Circuit_Name1=Aspen.Circuit OR Ar.Circuit_Name2=Aspen.Circuit) where AR.M3I_OBJECT_ID 
in (select DISTINCT M3I_OBJECT_ID from TCGACDS.GCM_CONN_DATA_STORE where M3I_ATTRIBUTE_EQUIP_TYPE='AUTOMATIC_RECLOSER_LOCATION')

UNION

select '1.3 Number of Recloser Objects that have PE Info from ASPEN' as category, count(DISTINCT RECLOSER_MRID) as COUNT, 'Info' as Comments  from TCGACDS.GCM_v_ASPEN_AR_DATA

UNION


select '1.4 Number of Recloser Objects that have PE Info from ASPEN but those recloser objects not in GCM connectivity' as category, count (DISTINCT AR.M3I_OBJECT_ID) as COUNT, 'Info' as Comments from TCGACDS.AUTOMATIC_RECLOSER_LOCATION AR
INNER JOIN
(SELECT DISTINCT CIRCUIT,LTRIM(EQUIPMENT_NUMBER,'0') as EQUIPMENT_NUMBER,KEY_GROUPNAME 
from TCGACDS.GCM_ASPEN_RELAY_SETTINGS where EQUIPMENT_TYPE in ('AR')) ASPEN
ON LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(AR.LINE_DEVICE_NO,'RAR'),'RSR'),'RIS'),'AR'),'0')=ASPEN.EQUIPMENT_NUMBER
and (Ar.Circuit_Name1=Aspen.Circuit OR Ar.Circuit_Name2=Aspen.Circuit) where AR.M3I_OBJECT_ID 
not in (select DISTINCT M3I_OBJECT_ID from TCGACDS.GCM_CONN_DATA_STORE where M3I_ATTRIBUTE_EQUIP_TYPE='AUTOMATIC_RECLOSER_LOCATION')

UNION

select '1.5 Recloser object Present in Distribution but not in ASPEN' as category, count(DISTINCT AR.M3I_OBJECT_ID) as COUNT, 'Info' as Comments  from TCGACDS.AUTOMATIC_RECLOSER_LOCATION AR
LEFT JOIN
(SELECT DISTINCT CIRCUIT,LTRIM(EQUIPMENT_NUMBER,'0') as EQUIPMENT_NUMBER,KEY_GROUPNAME 
from TCGACDS.GCM_ASPEN_RELAY_SETTINGS where EQUIPMENT_TYPE in ('AR')) ASPEN
ON LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(AR.LINE_DEVICE_NO,'RAR'),'RSR'),'RIS'),'AR'),'0')=ASPEN.EQUIPMENT_NUMBER
and (Ar.Circuit_Name1=Aspen.Circuit OR Ar.Circuit_Name2=Aspen.Circuit)
WHERE ASPEN.EQUIPMENT_NUMBER IS NULL

UNION

select '1.7 Recloser Equipment Present in ASPEN but not in Distribution' as category, count(DISTINCT ASPEN.EQUIPMENT_NUMBER) as COUNT, 'Info' as Comments   from TCGACDS.AUTOMATIC_RECLOSER_LOCATION AR
RIGHT JOIN
(SELECT DISTINCT CIRCUIT,LTRIM(EQUIPMENT_NUMBER,'0') as EQUIPMENT_NUMBER,KEY_GROUPNAME 
from TCGACDS.GCM_ASPEN_RELAY_SETTINGS where EQUIPMENT_TYPE in ('AR')) ASPEN
ON LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(AR.LINE_DEVICE_NO,'RAR'),'RSR'),'RIS'),'AR'),'0')=ASPEN.EQUIPMENT_NUMBER
and (Ar.Circuit_Name1=Aspen.Circuit OR Ar.Circuit_Name2=Aspen.Circuit)
WHERE AR.M3I_OBJECT_ID IS NULL and ASPEN.EQUIPMENT_NUMBER is NOT NULL

UNION

select '1.8 Number of Vac fault Interrupter objects from GESW' as category, count(DISTINCT M3I_OBJECT_ID) as COUNT, 'Info' as Comments from TCGACDS.VAC_FAULT_INTERRUPTER where Circuit_Name1 is not null

UNION

select '1.9 No.of Vac fault Interrupter objects in GCM connectivity' as category, count(DISTINCT M3I_OBJECT_ID) as COUNT, 'Info' as Comments  from TCGACDS.GCM_CONN_DATA_STORE where M3I_ATTRIBUTE_EQUIP_TYPE='VAC_FAULT_INTERRUPTER'

UNION


select '2.0 Number of Vac fault Interrupter Objects that should have PE Info from ASPEN' as category, count(DISTINCT VFI.M3I_OBJECT_ID)  as COUNT, 'Info' as Comments from TCGACDS.VAC_FAULT_INTERRUPTER VFI
INNER JOIN
(SELECT DISTINCT CIRCUIT,LTRIM(EQUIPMENT_NUMBER,'0') as EQUIPMENT_NUMBER,KEY_GROUPNAME 
from TCGACDS.GCM_ASPEN_RELAY_SETTINGS where EQUIPMENT_TYPE in ('VFI')) ASPEN
ON LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(VFI.LINE_DEVICE_NO,'VFI'),'RCI'),'RSI'),'VFI'),'0')=ASPEN.EQUIPMENT_NUMBER
and VFI.Circuit_Name1=Aspen.Circuit  where VFI.M3I_OBJECT_ID 
in (select DISTINCT M3I_OBJECT_ID from TCGACDS.GCM_CONN_DATA_STORE where M3I_ATTRIBUTE_EQUIP_TYPE='VAC_FAULT_INTERRUPTER')

UNION


select '2.1 Number of Vac fault Interrupter Objects that have PE Info from ASPEN' as category, count(DISTINCT VFI_MRID) as COUNT, 'Info' as Comments  from TCGACDS.GCM_v_ASPEN_VFI_DATA

UNION

select '2.2 Number of Vac fault Interrupter Objects that have PE Info from ASPEN but those VFI objects not in GCM connectivity' as category, count(DISTINCT VFI.M3I_OBJECT_ID) as COUNT, 'Info' as Comments  from TCGACDS.VAC_FAULT_INTERRUPTER VFI
INNER JOIN
(SELECT DISTINCT CIRCUIT,LTRIM(EQUIPMENT_NUMBER,'0') as EQUIPMENT_NUMBER,KEY_GROUPNAME 
from TCGACDS.GCM_ASPEN_RELAY_SETTINGS where EQUIPMENT_TYPE in ('VFI')) ASPEN
ON LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(VFI.LINE_DEVICE_NO,'VFI'),'RCI'),'RSI'),'VFI'),'0')=ASPEN.EQUIPMENT_NUMBER
and VFI.Circuit_Name1=Aspen.Circuit  where VFI.M3I_OBJECT_ID 
not in (select DISTINCT M3I_OBJECT_ID from TCGACDS.GCM_CONN_DATA_STORE where M3I_ATTRIBUTE_EQUIP_TYPE='VAC_FAULT_INTERRUPTER')

UNION


select '2.3 Vac fault Interrupter object Present in Distribution but not in ASPEN connectivity' as category, count(DISTINCT VFI.M3I_OBJECT_ID) as COUNT, 'Info' as Comments  from TCGACDS.VAC_FAULT_INTERRUPTER VFI
LEFT JOIN
(SELECT DISTINCT CIRCUIT,LTRIM(EQUIPMENT_NUMBER,'0') as EQUIPMENT_NUMBER,KEY_GROUPNAME 
from TCGACDS.GCM_ASPEN_RELAY_SETTINGS where EQUIPMENT_TYPE in ('VFI')) ASPEN
ON LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(VFI.LINE_DEVICE_NO,'VFI'),'RCI'),'RSI'),'VFI'),'0')=ASPEN.EQUIPMENT_NUMBER
and VFI.Circuit_Name1=Aspen.Circuit  
WHERE ASPEN.EQUIPMENT_NUMBER IS NULL

UNION

select '2.4 Vac fault Interrupter Equipment Present in ASPEN but not in Distribution' as category,count(DISTINCT VFI.M3I_OBJECT_ID)  as COUNT, 'Info' as Comments from TCGACDS.VAC_FAULT_INTERRUPTER VFI
RIGHT JOIN
(SELECT DISTINCT CIRCUIT,LTRIM(EQUIPMENT_NUMBER,'0') as EQUIPMENT_NUMBER,KEY_GROUPNAME 
from TCGACDS.GCM_ASPEN_RELAY_SETTINGS where EQUIPMENT_TYPE in ('VFI')) ASPEN
ON LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(VFI.LINE_DEVICE_NO,'VFI'),'RCI'),'RSI'),'VFI'),'0')=ASPEN.EQUIPMENT_NUMBER
and VFI.Circuit_Name1=Aspen.Circuit 
WHERE VFI.M3I_OBJECT_ID IS NULL and ASPEN.EQUIPMENT_NUMBER is NOT NULL;

