SELECT DISTINCT PRIMARY_CKT,VERSION FROM TCGACDS.GCM_CONN_DATA_STORE where version is not null
MINUS
SELECT DISTINCT ELEMENT_NAME,VERSION FROM TCGACDS.GCM_GEOSPATIAL_FILE_STATUS WHERE STATUS='COMPLETED' AND ELEMENT_TYPE='CIRCUIT';