--Validate Net_9REf$ table data not in Base tables,Dist network
--FOr test case to pass we should have zero count for all below count o/p  
-- Last Modified date: 04/10/2023
-----------------------------------------------------------


column Category heading "Category" Format a51
column COUNT heading "COUNT" Format a9
column Comments heading "Comment" Format a10
-----------------


Select  '1.1-AUTOMATIC_RECLOSER:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='AUTOMATIC_RECLOSER' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.AUTOMATIC_RECLOSER B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '1.2-AUTOMATIC_RECLOSER_LOCATION:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='AUTOMATIC_RECLOSER_LOCATION' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.AUTOMATIC_RECLOSER_LOCATION B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '1.3-BRANCH_LINE_FUSE:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='BRANCH_LINE_FUSE' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.BRANCH_LINE_FUSE B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '1.4-CAPACITOR_BANK:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='CAPACITOR_BANK' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.CAPACITOR_BANK B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '1.5-CIRCUIT_HEAD:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='CIRCUIT_HEAD' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.CIRCUIT_HEAD B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '1.6-DISTRIBUTION_HYPERNODE:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='DISTRIBUTION_HYPERNODE' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.DISTRIBUTION_HYPERNODE B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '1.7-ELBOW:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='ELBOW' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.ELBOW B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '1.8-ENDBELL:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='ENDBELL' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.ENDBELL B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '1.9-FAULT_INDICATOR:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='FAULT_INDICATOR' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.FAULT_INDICATOR B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '2.1-FAULT_INTERRUPTER:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='FAULT_INTERRUPTER' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.FAULT_INTERRUPTER B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '2.2-FAULT_INTERRUPTER_LOCATION:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='FAULT_INTERRUPTER_LOCATION' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.FAULT_INTERRUPTER_LOCATION B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '2.3-FEED_POINT:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='FEED_POINT' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.FEED_POINT B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '2.4-FUSED_CUTOUT:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='FUSED_CUTOUT' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.FUSED_CUTOUT B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '2.5-GROUND_BANK:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='GROUND_BANK' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.GROUND_BANK B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '2.6-IBANK:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='IBANK' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.IBANK B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '2.7-IBANK_LOCATION:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='IBANK_LOCATION' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.IBANK_LOCATION B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '2.8-JUNCTION_BAR:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='JUNCTION_BAR' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.JUNCTION_BAR B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '2.9-JUNCTION_BAR_LOCATION:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='JUNCTION_BAR_LOCATION' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.JUNCTION_BAR_LOCATION B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '3.1-JUNCTION_BAR_PIN:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='JUNCTION_BAR_PIN' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.JUNCTION_BAR_PIN B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '3.2-LINE_SUB:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='LINE_SUB' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.LINE_SUB B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '3.3-NETCOM_MONITOR:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='NETCOM_MONITOR' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.NETCOM_MONITOR B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '3.4-NETWORK_PROTECTOR:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='NETWORK_PROTECTOR' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.NETWORK_PROTECTOR B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '3.5-OH_PRIMARY_CONDUCTOR:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='OH_PRIMARY_CONDUCTOR' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.OH_PRIMARY_CONDUCTOR B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '3.6-OH_SWITCH:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='OH_SWITCH' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.OH_SWITCH B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '3.7-OH_TRANSFORMER:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='OH_TRANSFORMER' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.OH_TRANSFORMER B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '3.8-OH_TRANSFORMER_LOCATION:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='OH_TRANSFORMER_LOCATION' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.OH_TRANSFORMER_LOCATION B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '3.9-PE_GEAR_SWITCH:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='PE_GEAR_SWITCH' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.PE_GEAR_SWITCH B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '4.1-PE_GEAR_SWITCH_LOCATION:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='PE_GEAR_SWITCH_LOCATION' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.PE_GEAR_SWITCH_LOCATION B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '4.2-PE_GEAR_SWITCH_PIN:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='PE_GEAR_SWITCH_PIN' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.PE_GEAR_SWITCH_PIN B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '4.3-POTHEAD:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='POTHEAD' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.POTHEAD B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '4.4-PRIMARY_METER:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='PRIMARY_METER' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.PRIMARY_METER B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '4.5-PRIMARY_METER_LOCATION:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='PRIMARY_METER_LOCATION' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.PRIMARY_METER_LOCATION B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '4.6-TAP:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='TAP' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.TAP B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '4.7-TIE_CABLE:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='TIE_CABLE' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.TIE_CABLE B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '4.8-UG_BUS:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='UG_BUS' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.UG_BUS B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '4.9-UG_PRIMARY_CONDUCTOR:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='UG_PRIMARY_CONDUCTOR' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.UG_PRIMARY_CONDUCTOR B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '5.1-UG_SWITCH:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='UG_SWITCH' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.UG_SWITCH B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '5.2-UG_SWITCH_LOCATION:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='UG_SWITCH_LOCATION' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.UG_SWITCH_LOCATION B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '5.3-UG_SWITCH_PIN:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='UG_SWITCH_PIN' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.UG_SWITCH_PIN B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '5.4-UG_TRANSFORMER:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='UG_TRANSFORMER' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.UG_TRANSFORMER B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '5.5-UG_TRANSFORMER_LOCATION:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='UG_TRANSFORMER_LOCATION' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.UG_TRANSFORMER_LOCATION B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '5.6-VAC_FAULT_INTERRUPTER:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='VAC_FAULT_INTERRUPTER' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.VAC_FAULT_INTERRUPTER B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '5.7-VOLTAGE_REGULATOR:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='VOLTAGE_REGULATOR' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.VOLTAGE_REGULATOR B WHERE B.ID=A.FEATURE_IDENTIFIER))
UNION
Select  '5.8-VOLTAGE_REGULATOR_LOCATION:Data in net_9_ref$,but not in base table' as Category, count(*) as count, CASE WHEN COUNT(*) > 0 THEN 'Failed'ELSE 'Passed' END as Comments
FROM TCGACDS.GCM_CONNECTIVITY WHERE FEATURE_ID IN (
SELECT DISTINCT FEATURE_IDENTIFIER FROM TCGACDS.NET_9_REF$ A WHERE A.FEATURE_TABLE='VOLTAGE_REGULATOR_LOCATION' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.VOLTAGE_REGULATOR_LOCATION B WHERE B.ID=A.FEATURE_IDENTIFIER))