SET PAGESIZE 10000
SET FEED OFF
SET LINESIZE 160

column Validations heading "Validations" Format A120
column COUNT heading "COUNT" Format 9999999999
column Remarks heading "Remarks" Format A20


SELECT 'Validating a record got instered in the DER process status table'  AS Validations , REC_COUNT AS COUNT,
(CASE WHEN REC_COUNT >= 1 THEN 'PASS' ELSE 'FAIL' END) AS Remarks FROM (
SELECT count(*) AS REC_COUNT FROM  TCGACDS.GCM_DER_PROCESS_STATUS 
WHERE INGESTION_COMPLETE_STATUS ='Y' AND JOBNAME = 'INVERTER FILE INGESTION' AND 
jobid in (SELECT max(jobid) FROM  TCGACDS.GCM_DER_PROCESS_STATUS 
WHERE JOBNAME = 'INVERTER FILE INGESTION' AND INGESTION_COMPLETE_STATUS ='Y'))
union
SELECT 'Finding the reason for the unsuccessful File is ingestion'  AS Validations ,
(CASE WHEN Status ='N' THEN 1 ELSE 0 END) AS COUNT,
(CASE WHEN Status ='Y' THEN 'File Ingestion Successful' else Reason END) AS Remarks FROM (
SELECT Remarks AS Reason, INGESTION_COMPLETE_STATUS AS Status FROM  TCGACDS.GCM_DER_PROCESS_STATUS 
WHERE JOBNAME = 'INVERTER FILE INGESTION' AND 
jobid in (SELECT MAX(jobid) FROM  TCGACDS.GCM_DER_PROCESS_STATUS 
WHERE JOBNAME = 'INVERTER FILE INGESTION'))
union
SELECT 'Total Record count in the Input DER File' AS Validations, TOTAL_COUNT AS COUNT,'INFO' AS REMARKS
FROM TCGACDS.GCM_DER_PROCESS_STATUS WHERE JOBID IN (
SELECT MAX(JOBID) FROM TCGACDS.GCM_DER_PROCESS_STATUS WHERE JOBNAME = 'INVERTER FILE INGESTION' 
AND INGESTION_COMPLETE_STATUS ='Y')
union
SELECT 'Total Record count in the Input DER File excluding duplicates ' AS Validations, FEATURE_COUNT AS COUNT,'INFO' AS REMARKS
FROM TCGACDS.GCM_DER_PROCESS_STATUS WHERE JOBID IN (
SELECT MAX(JOBID) FROM TCGACDS.GCM_DER_PROCESS_STATUS WHERE JOBNAME = 'INVERTER FILE INGESTION' 
AND INGESTION_COMPLETE_STATUS ='Y')
union
SELECT 'Duplicate record in the input DER file' AS Validations, TO_NUMBER(DUPLICATE_COUNT) AS COUNT,
(CASE WHEN DUPLICATE_COUNT> 0 THEN 'FAIL' WHEN DUPLICATE_COUNT =0  THEN 'PASS' END) AS REMARKS
FROM TCGACDS.GCM_DER_PROCESS_STATUS WHERE JOBID IN (
SELECT MAX(JOBID) FROM TCGACDS.GCM_DER_PROCESS_STATUS WHERE JOBNAME = 'INVERTER FILE INGESTION' 
AND INGESTION_COMPLETE_STATUS ='Y')
union
SELECT 'Total number of records loaded into GCM_DER_INVERTER_DATA ' AS Validations, 
INVERTER_DATA_COUNT AS COUNT,
(CASE WHEN PROCESS_STATUS_COUNT = INVERTER_DATA_COUNT THEN 'PASS' ELSE 'FAIL' END) AS REMARKS FROM
(
SELECT
FEATURE_COUNT as PROCESS_STATUS_COUNT,
(select count(*)  from  TCGACDS.GCM_DER_INVERTER_DATA) as INVERTER_DATA_COUNT
from TCGACDS.GCM_DER_PROCESS_STATUS
where JOBID IN (
SELECT MAX(JOBID) FROM TCGACDS.GCM_DER_PROCESS_STATUS  WHERE JOBNAME = 'INVERTER FILE INGESTION' 
AND INGESTION_COMPLETE_STATUS ='Y'))
union
SELECT 'Validate the latest file name manually from: 
\\sce\workgroup\AppData\ GCMR3Prod\DER_Data\GRIDMOD\OUTBOUND\DER_INTERCONNECTION_LOOKUP' AS Validations , 0 AS COUNT,
'Expected file name:' || FILENAME AS Remarks FROM (
SELECT FILENAME FROM  TCGACDS.GCM_DER_PROCESS_STATUS 
WHERE INGESTION_COMPLETE_STATUS ='Y' AND JOBNAME = 'INVERTER FILE INGESTION' AND 
jobid in (SELECT max(jobid) FROM  TCGACDS.GCM_DER_PROCESS_STATUS 
WHERE JOBNAME = 'INVERTER FILE INGESTION' AND INGESTION_COMPLETE_STATUS ='Y'));
