-- This report validates Distribution reasons for different fallout
-- Last Modified date: 4/24/2023
----------------------------------------------------------------------------------------------

column Category heading "Category" Format a51
column COUNT heading "COUNT" Format a9
column Comments heading "Comment" Format a10

 SELECT '1.0-Equipment count having ASPEN AR DATA' as Category, COUNT (DISTINCT M3I_OBJECT_ID) as COUNT
 FROM TCGACDS.AUTOMATIC_RECLOSER_LOCATION
 WHERE NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_V_ASPEN_AR_DATA V WHERE V.RECLOSER_MRID=M3I_OBJECT_ID)
 
 UNION
 
SELECT '1.1-Equipment count having ASPEN VFI DATA' as Category, COUNT (DISTINCT M3I_OBJECT_ID) as COUNT
  FROM TCGACDS.VAC_FAULT_INTERRUPTER VFI 
 WHERE NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_V_ASPEN_VFI_DATA V WHERE V.VFI_MRID=VFI.M3I_OBJECT_ID) 
 
 UNION
--Ground and Phase trip information is found missing 
SELECT '1.2-Ground and Phase trip information is found missing#' as Category, COUNT (DISTINCT WORLD_OWNER_ID) as COUNT
  FROM TCGACDS.AUTOMATIC_RECLOSER REC INNER JOIN TCGACDS.AUTOMATIC_RECLOSER_LOCATION LOC ON LOC.ID = REC.WORLD_OWNER_ID 
       LEFT OUTER JOIN TCGACDS.ECM001_DMS_RECLSR_SETNGS DREC ON REC.M3I_OBJECT_ID = DREC.DEVICE_ID
       LEFT OUTER JOIN TCGACDS.GCM_V_RECLOSER V ON LOC.LINE_DEVICE_NO = V.LINE_DEVICE_NO AND LOC.STRUCTURE_NUMBER = V.STRUCTURE_NUMBER
 WHERE (V.GROUND_TRIP_RATING IS NULL OR V.PHASE_TRIP_RATING IS NULL)
UNION
--Voltage Regulator queries:
--Vregs in Dist Connectivity but not in VREG
SELECT '1.3-Vregs in Dist Connectivity but not in VREG#' as Category, COUNT (DISTINCT M3I_OBJECT_ID) as COUNT
FROM TCGACDS.GCM_CONN_DATA_STORE CDS 
 WHERE NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_VREG_DATA VREG WHERE VREG.STRUCTURE_NUMBER=CDS.STRUCTURE_NUMBER)
   AND CDS.ASSET_TYPE='VOLTAGE_REGULATOR'
   
UNION
--Vregs in VREG but not present in Dist Connectivity 
SELECT '1.4-Vregs in VREG but not present in Dist Connectivity#' as Category, COUNT (DISTINCT STRUCTURE_NUMBR) as COUNT
  FROM TCGACDS.GCM_VREG_DATA VREG LEFT OUTER JOIN TCGACDS.GCM_STRUCTUREFEEDERINFO SFI ON VREG.STRUCTURE_NUMBER=SFI.STRUCTURE_NUMBR
 WHERE NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_CONN_DATA_STORE CDS WHERE CDS.STRUCTURE_NUMBER=VREG.STRUCTURE_NUMBER AND CDS.ASSET_TYPE='VOLTAGE_REGULATOR');