SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
V_CHANGE_DATE TIMESTAMP(6);
BEGIN

select DISTINCT TRUNC(CHANGE_DATE) INTO V_CHANGE_DATE from TCGACDS.GCM_VREG_LINE_DATA_TRANSACTION WHERE PROCESSED_FLAG='N';
select COUNT(1) INTO V_COUNT from TCGACDS.GCM_VREG_LINE_DATA_TRANSACTION WHERE PROCESSED_FLAG='N';

IF V_COUNT<>0 
THEN
DBMS_OUTPUT.PUT_LINE('DVVC LOAD SUCCESSFUL ' ||' '||V_CHANGE_DATE||' '|| V_COUNT );
ELSE
DBMS_OUTPUT.PUT_LINE('DVVC LOAD NEED TO VALIDATE ' ||' '||V_CHANGE_DATE||' '|| V_COUNT );
END IF ;
END;
/