SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
V_CNT NUMBER;
BEGIN
SELECT COUNT (1) INTO V_COUNT FROM (SELECT * FROM TCGACDS.GCM_SUB_I_CONN_SUBSTATIONS WHERE MRID NOT IN 
(SELECT MRID FROM TCGACDS.GCM_V_SUB_I_SUBSTATION WHERE GCM_SOR='EMS' AND TYP IS NOT NULL)
AND SOR='EMS');
SELECT COUNT (1) INTO V_CNT FROM (SELECT * FROM TCGACDS.GCM_V_SUB_I_SUBSTATION WHERE GCM_SOR='EMS' AND TYP IS NOT NULL
AND MRID NOT IN (SELECT MRID FROM TCGACDS.GCM_SUB_I_CONN_SUBSTATIONS WHERE SOR ='EMS'));
IF V_COUNT=0  AND V_CNT=0
THEN
DBMS_OUTPUT.PUT_LINE('EMS INITIAL LOAD  SUCCESSFUL ' || V_COUNT ||' '|| V_CNT);
ELSE
DBMS_OUTPUT.PUT_LINE('EMS INITIAL LOAD NEED TO VALIDATE ' || V_COUNT ||' '|| V_CNT);
END IF ;
END;
/

DECLARE 
V_COUNT NUMBER;
BEGIN

SELECT COUNT (1) INTO V_COUNT FROM TCGACDS.GCM_SUB_I_CONN_SUBSTATIONS WHERE SOR='GESW';
IF V_COUNT<>0 
THEN
DBMS_OUTPUT.PUT_LINE('EMS INITIAL LOAD  SUCCESSFUL ' || V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('EMS INITIAL LOAD NEED TO VALIDATE ' || V_COUNT);
END IF ;
END;
/
