--BEFORE INITIAL LOAD--

DECLARE
V_NUM NUMBER;
V_SAP NUMBER;
BEGIN
SELECT COUNT(1) INTO V_NUM FROM TCGACDS.GCM_SUB_DIST_JOB_STATUS WHERE CURRENT_JOB='Y';
IF V_NUM>0
THEN UPDATE TCGACDS.GCM_SUB_DIST_JOB_STATUS SET CURRENT_JOB='N', SUCCESS='Y' WHERE CURRENT_JOB='Y';
COMMIT;
END IF;
SELECT COUNT(1) INTO V_SAP FROM TCGACDS.GCM_SUB_I_SAP_PROCESS WHERE CURRENT_JOB='Y';
IF V_SAP>0
THEN UPDATE TCGACDS.GCM_SUB_I_SAP_PROCESS SET CURRENT_JOB='N', SUCCESS_FLAG='Y' WHERE CURRENT_JOB='Y';
COMMIT;
END IF;
END;
/
--BEFORE RDF RUN--

DECLARE
V_NUM NUMBER;
BEGIN
SELECT COUNT(1) INTO V_NUM FROM TCGACDS.GCM_PROCESS_STATUS WHERE INGESTION_READY='N';
IF V_NUM>0 THEN 
 UPDATE TCGACDS.GCM_PROCESS_STATUS SET INGESTION_READY='Y' WHERE INGESTION_READY='N';
COMMIT;
END IF;
END;
/
------------------------------------------------------------------------------------------------------
DECLARE
V_NUM NUMBER;
V_SAP NUMBER;
BEGIN
SELECT COUNT(1) INTO V_NUM FROM TCGACDS.GCM_SUB_DIST_JOB_STATUS WHERE CURRENT_JOB='Y';
IF V_NUM>0
THEN UPDATE TCGACDS.GCM_SUB_DIST_JOB_STATUS SET CURRENT_JOB='N', SUCCESS='Y' WHERE CURRENT_JOB='Y';
COMMIT;
END IF;
SELECT COUNT(1) INTO V_SAP FROM TCGACDS.GCM_SUB_I_SAP_PROCESS WHERE CURRENT_JOB='Y';
IF V_SAP>0
THEN UPDATE TCGACDS.GCM_SUB_I_SAP_PROCESS SET CURRENT_JOB='N', SUCCESS_FLAG='Y' WHERE CURRENT_JOB='Y';
COMMIT;
END IF;
END;
/