alter session set current_schema=tcgacds;


select * from gcm_dist_job_log order by START_DTTM desc;
-------------Feeder------------------
--In DS Table
select count(*) from GCM_SCIM_DIST_FEEDER_DS;---4455
--In STG
select count(*) from circuit_head;-----4459

select * from GCM_SCIM_DIST_FEEDER_DS where FEEDER_STATUS_VLU='REMOVED';
--Duplicate check
select count(distinct FEEDER_LOOKUPID) from GCM_SCIM_DIST_FEEDER_DS;---4455

--FALLOUTS
select count(*)from TCGACDS.circuit_head ch where not exists 
 (select * from TCGACDS.GCM_SCIM_DIST_FEEDER_DS ds 
 where FEEDER_STATUS_VLU<>'REMOVED' and ch.CIRCT_ID=ds.FEEDER_CIRCUITID);

--------XFMR------------------


-----------------------------
--IN STG
select count( distinct ID) from TCGACDS.GCM_V_M2G_TRANSFORMER_scim ;--647466
--IN DS
select COUNT(DISTINCT TRANSFORMERBANKIDENTIFIER_NAME) from GCM_SCIM_DIST_STRUCTXFM_DS 
where TRANSFOMERBANK_STATUS_VLU<>'REMOVED';--649029
-----------------------------


-----------------------------
--ORPHAN RECORDS
select distinct TRANSFORMERBANKIDENTIFIER_NAME,TRANSFORMERBANK_TYP from GCM_SCIM_DIST_STRUCTXFM_DS ds 
where  TRANSFOMERBANK_STATUS_VLU<>'REMOVED' and not exists (select 1 from GCM_V_M2G_TRANSFORMER_scim sc 
where sc.id =ds.TRANSFORMERBANKIDENTIFIER_NAME);
--FALLOUT
select * from GCM_V_M2G_TRANSFORMER_scim  sc where not exists (
select  TRANSFORMERBANK_MRID from GCM_SCIM_DIST_STRUCTXFM_DS ds 
where  TRANSFOMERBANK_STATUS_VLU<>'REMOVED' and sc.id =ds.TRANSFORMERBANKIDENTIFIER_NAME);
-----------------------------



-------------POWERXFMR----------
--IN STG
select COUNT(DISTINCT id) from TCGACDS.GCM_V_M2G_TRANSFORMER_UNT_SCIM ;--747810
--IN DS
select COUNT(DISTINCT POWERTRANSFOMERIDENTIFIER_NAME)PXFMR_DS from TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS 
where POWERTRANSFOMER_STATUS_VLU<>'REMOVED';--747805

--ORPHAN RECORDS
select  COUNT(DISTINCT POWERTRANSFOMERIDENTIFIER_NAME)PXFMR_ORPHAN from TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS 
where POWERTRANSFOMER_STATUS_VLU<>'REMOVED' and POWERTRANSFOMERIDENTIFIER_NAME  not in (select  id from TCGACDS.GCM_V_M2G_TRANSFORMER_UNT_SCIM);--2

--FALLOUTS
select COUNT(*) PXFMR_FALLOUT from TCGACDS.GCM_V_M2G_TRANSFORMER_UNT_SCIM where id not in 
 (select  POWERTRANSFOMERIDENTIFIER_NAME from TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS 
where POWERTRANSFOMER_STATUS_VLU<>'REMOVED')
AND ID IN (SELECT RECORD_ID FROM TCGACDS.SWSYNC_TRANSACTION WHERE PROCESS_DATE>SYSDATE-1 );--28
SELECT RECORD_ID FROM SWSYNC_TRANSACTION WHERE PROCESS_DATE>SYSDATE-1;



--USAGEPOINT_LOOKUPID
--IN DS
SELECT COUNT(DISTINCT USAGEPOINT_NUMBER) FROM GCM_SCIM_DIST_USAGEPOINT_DS ;--5136445
--IN STG
SELECT COUNT( DISTINCT ISVC_NUM)
                      FROM ODS030_METER_DTLS
                      WHERE MAPPER_ACTION_FLAG <> 'REMOVE' AND SERVICE_TYPE_CODE = 'E' ;--5136622
--FALLOUT
SELECT *-- COUNT( DISTINCT ISVC_NUM)
  FROM ODS030_METER_DTLS
  WHERE MAPPER_ACTION_FLAG <> 'REMOVE' AND SERVICE_TYPE_CODE = 'E'  and isvc_num not in (select USAGEPOINT_NUMBER from GCM_SCIM_DIST_USAGEPOINT_DS) ;--287

--ORPHAN RECORDS
select count(*) from GCM_SCIM_DIST_USAGEPOINT_DS where USAGEPOINT_NUMBER not in (SELECT isvc_num
  FROM ODS030_METER_DTLS
  WHERE MAPPER_ACTION_FLAG <> 'REMOVE' AND SERVICE_TYPE_CODE = 'E');--110

--Fallouts 


select A.* from (select A.*,RANK() over (PARTITION BY isvc_num order by created_date desc) as rank_no
from ods030_meter_dtls A)A where A.rank_no=1 and A.mapper_action_flag<> 'REMOVE' and A.SERVICE_TYPE_CODE='E' and A.isvc_num not in 
(select USAGEPOINT_NUMBER from GCM_SCIM_DIST_USAGEPOINT_DS) and exists (select 1 from GCM_V_M2G_TRANSFORMER_SCIM where id=xfmr_bank_id);

  
 --SUBSTATION 
  
 --sub_stg 
  select count(*) from TCGACDS.substation;
  
--sub_ds
select COUNT(*) from TCGACDS.gcm_scim_dist_SUBSTATION_DS;

--SUB_ORPHAN
select count(SUBSTATION_LOOKUPID) from  TCGACDS.gcm_scim_dist_SUBSTATION_DS D where not exists
(select 1 FROM TCGACDS.SUBSTATION S WHERE S.SUBSTATION_NO=D.SUBSTATION_NUMBER);

--SUB_FALLOUT
SELECT COUNT(SUBSTATION_NO) FROM  TCGACDS.SUBSTATION S WHERE NOT EXISTS
(SELECT 1 FROM TCGACDS.gcm_scim_dist_SUBSTATION_DS D WHERE S.SUBSTATION_NO=D.SUBSTATION_NUMBER);




  