SET PAGESIZE 10000
SET FEED OFF
SET LINESIZE 160

column Validations heading "Validations" Format A120
column COUNT heading "COUNT" Format 9999999999
column Remarks heading "Remarks" Format A20

SELECT 'Validating a record got instered in the Log Table gcm_dist_job_log(Job name -GCM_STG_SCIM_INIT)'  AS Validations , 
REC_COUNT AS COUNT,
(CASE WHEN REC_COUNT >= 1 THEN 'PASS' ELSE 'FAIL' END) AS Remarks FROM (
SELECT count(*) AS REC_COUNT FROM  TCGACDS.GCM_DIST_JOB_LOG 
WHERE JOB_NAME ='GCM_STG_SCIM_INIT' AND STATUS = 'SUCCESS' AND 
JOB_LOG_ID in (SELECT max(JOB_LOG_ID) FROM  TCGACDS.GCM_DIST_JOB_LOG 
WHERE JOB_NAME ='GCM_STG_SCIM_INIT' AND STATUS = 'SUCCESS'))
union
SELECT 'Validating a record got instered in the Log Table gcm_dist_job_log (Job name -GCM_SCIM_DS)'  AS Validations , 
REC_COUNT AS COUNT,
(CASE WHEN REC_COUNT >= 1 THEN 'PASS' ELSE 'FAIL' END) AS Remarks FROM (
SELECT count(*) AS REC_COUNT FROM  TCGACDS.GCM_DIST_JOB_LOG 
WHERE JOB_NAME ='GCM_SCIM_DS' AND STATUS = 'SUCCESS' AND 
JOB_LOG_ID in (SELECT max(JOB_LOG_ID) FROM  TCGACDS.GCM_DIST_JOB_LOG 
WHERE JOB_NAME ='GCM_SCIM_DS' AND STATUS = 'SUCCESS'))
union
SELECT 'Total Number of record got inserted into Feeder DS Table' AS Validations, FEEDER_COUNT AS COUNT,
'Info' AS REMARKS FROM
(SELECT COUNT(*) AS FEEDER_COUNT FROM TCGACDS.GCM_SCIM_DIST_FEEDER_DS)
union
SELECT 'Validating if duplicate record got inserted into Feeder DS Table' AS Validations, 
FEEDER_COUNT-UNIQUE_FEEDER_COUNT AS COUNT,
(CASE WHEN FEEDER_COUNT-UNIQUE_FEEDER_COUNT >= 1 THEN 'FAIL' ELSE 'PASS' END) AS  REMARKS FROM
(SELECT
(SELECT COUNT(DISTINCT FEEDER_LOOKUPID) FROM TCGACDS.GCM_SCIM_DIST_FEEDER_DS) AS UNIQUE_FEEDER_COUNT,
FEEDER_COUNT
FROM 
(SELECT COUNT(*) AS FEEDER_COUNT FROM TCGACDS.GCM_SCIM_DIST_FEEDER_DS))
union
SELECT 'Feeder details present in CIRCUIT_HEAD but not present in GCM_SCIM_DIST_FEEDER_DS ' AS Validations, 
FEEDER_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT COUNT(*) AS FEEDER_COUNT from TCGACDS.CIRCUIT_HEAD ch WHERE NOT EXISTS
(SELECT * FROM TCGACDS.GCM_SCIM_DIST_FEEDER_DS ds 
WHERE FEEDER_STATUS_VLU<>'REMOVED' and ch.CIRCT_ID=ds.FEEDER_CIRCUITID))
union
SELECT 'Total Count of distinct Transformer present in the staging table GCM_V_M2G_TRANSFORMER_SCIM' AS Validations, 
XFMR_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT  COUNT(DISTINCT ID) AS XFMR_COUNT from TCGACDS.GCM_V_M2G_TRANSFORMER_SCIM)
union
SELECT 'Count of distinct Transformer present in the DS table GCM_SCIM_DIST_STRUCTXFM_DS' AS Validations, 
XFMR_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT COUNT(DISTINCT TRANSFORMERBANKIDENTIFIER_NAME) AS XFMR_COUNT from TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS 
WHERE TRANSFOMERBANK_STATUS_VLU<>'REMOVED')
union
SELECT 'Transformer count present in the DS table but not present in the Staging Table - ORPHAN RECORDS' AS Validations, 
XFMR_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT COUNT(*) AS XFMR_COUNT FROM ( 
SELECT DISTINCT TRANSFORMERBANKIDENTIFIER_NAME,TRANSFORMERBANK_TYP 
FROM TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS ds WHERE  TRANSFOMERBANK_STATUS_VLU<>'REMOVED' AND NOT EXISTS
(SELECT 1 FROM TCGACDS.GCM_V_M2G_TRANSFORMER_SCIM sc 
WHERE sc.id =ds.TRANSFORMERBANKIDENTIFIER_NAME)))
union
SELECT 'Transformer count present in the Staging table but not present in the DS Table - FALLOUT RECORDS' AS Validations, 
XFMR_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT COUNT(*) AS XFMR_COUNT FROM (
SELECT * FROM TCGACDS.GCM_V_M2G_TRANSFORMER_SCIM  sc WHERE NOT EXISTS (
SELECT  TRANSFORMERBANK_MRID from TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS ds 
WHERE  TRANSFOMERBANK_STATUS_VLU<>'REMOVED' AND sc.ID =ds.TRANSFORMERBANKIDENTIFIER_NAME)))
union
SELECT 'Total Count of distinct Power Transformer present in the staging table GCM_V_M2G_TRANSFORMER_UNT_SCIM' AS Validations, 
POWER_XFMR_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
select COUNT(DISTINCT ID) AS POWER_XFMR_COUNT from TCGACDS.GCM_V_M2G_TRANSFORMER_UNT_SCIM)
union
SELECT 'Total Count of distinct Power Transformer present in the DS table GCM_SCIM_DIST_STRUCTXFM_DS' AS Validations, 
POWER_XFMR_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT COUNT(DISTINCT POWERTRANSFOMERIDENTIFIER_NAME) AS POWER_XFMR_COUNT FROM TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS 
where POWERTRANSFOMER_STATUS_VLU<>'REMOVED')
union
SELECT 'Power Transformer Count present in the DS table but not present in the Staging Table - ORPHAN RECORDS' AS Validations, 
POWER_XFMR_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT COUNT(*) AS POWER_XFMR_COUNT FROM ( 
SELECT  COUNT(DISTINCT POWERTRANSFOMERIDENTIFIER_NAME) from TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS 
where POWERTRANSFOMER_STATUS_VLU<>'REMOVED' and POWERTRANSFOMERIDENTIFIER_NAME  not in 
(SELECT  id from TCGACDS.GCM_V_M2G_TRANSFORMER_UNT_SCIM)))
union
SELECT 'Power Transformer count present in the Staging table but not present in the DS Table - FALLOUT RECORDS' AS Validations, 
PXFMR_FALLOUT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT COUNT(*) AS PXFMR_FALLOUT from TCGACDS.GCM_V_M2G_TRANSFORMER_UNT_SCIM where id not in 
(SELECT  POWERTRANSFOMERIDENTIFIER_NAME from TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS 
where POWERTRANSFOMER_STATUS_VLU<>'REMOVED')
AND ID IN (SELECT RECORD_ID FROM TCGACDS.SWSYNC_TRANSACTION WHERE PROCESS_DATE>SYSDATE-1 ))
union
SELECT 'Total Count of distinct Usagepoint present in the DS table GCM_SCIM_DIST_USAGEPOINT_DS' AS Validations, 
USAGEPOINT_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT COUNT(DISTINCT USAGEPOINT_NUMBER) AS USAGEPOINT_COUNT FROM TCGACDS.GCM_SCIM_DIST_USAGEPOINT_DS)
union
SELECT 'Total Count of distinct circuit present in the Staging table ODS030_METER_DTLS' AS Validations, 
ISVCNUM_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT COUNT( DISTINCT ISVC_NUM) AS ISVCNUM_COUNT FROM TCGACDS.ODS030_METER_DTLS
WHERE MAPPER_ACTION_FLAG <> 'REMOVE' AND SERVICE_TYPE_CODE = 'E')
union
SELECT 'Circuit present in the DS table but not present in the Staging Table - ORPHAN RECORDS' AS Validations, 
USAGEPOINT_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
select count(*) AS USAGEPOINT_COUNT from TCGACDS.GCM_SCIM_DIST_USAGEPOINT_DS where USAGEPOINT_NUMBER 
not in (SELECT TO_CHAR(isvc_num)
  FROM TCGACDS.ODS030_METER_DTLS
  WHERE MAPPER_ACTION_FLAG <> 'REMOVE' AND SERVICE_TYPE_CODE = 'E'))
union
SELECT 'Circuit present in the Staging table but not present in the DS Table - FALLOUT RECORDS' 
AS Validations, 
USAGEPOINT_COUNT AS COUNT,'Info' AS  REMARKS FROM (
Select count(*) AS USAGEPOINT_COUNT FROM (
select A.* from (select A.*,RANK() over (PARTITION BY isvc_num order by created_date desc) as rank_no
from TCGACDS.ods030_meter_dtls A)A where A.rank_no=1 and A.mapper_action_flag<> 'REMOVE' 
and A.SERVICE_TYPE_CODE='E' and TO_CHAR(A.isvc_num) not in 
(select USAGEPOINT_NUMBER from TCGACDS.GCM_SCIM_DIST_USAGEPOINT_DS) and 
exists (select 1 from TCGACDS.GCM_V_M2G_TRANSFORMER_SCIM where id=xfmr_bank_id)))
union
SELECT 'Total Count of substation details present in the staging table SUBSTATION' AS Validations, 
SUBSTATION_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
select count(*) AS SUBSTATION_COUNT from TCGACDS.SUBSTATION)
union
SELECT 'Total Count of substation details present in the DS table GCM_SCIM_DIST_SUBSTATION_DS' AS Validations, 
SUBSTATION_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
select COUNT(*) AS SUBSTATION_COUNT from TCGACDS.GCM_SCIM_DIST_SUBSTATION_DS)
union
SELECT 'Total Count of substation details present in the DS table but not present in the Staging Table - ORPHAN RECORDS' AS Validations, 
SUBSTATION_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
select count(SUBSTATION_LOOKUPID) AS SUBSTATION_COUNT from  TCGACDS.GCM_SCIM_DIST_SUBSTATION_DS D where not exists
(select 1 FROM TCGACDS.SUBSTATION S WHERE S.SUBSTATION_NO=D.SUBSTATION_NUMBER))
union
SELECT 'Total Count of substation details present In the Staging table but not present in the DS Table - FALLOUT RECORDS' AS Validations, 
SUBSTATION_COUNT AS COUNT,
'Info' AS  REMARKS FROM (
SELECT COUNT(SUBSTATION_NO) AS SUBSTATION_COUNT FROM  TCGACDS.SUBSTATION S WHERE NOT EXISTS
(SELECT 1 FROM TCGACDS.gcm_scim_dist_SUBSTATION_DS D WHERE S.SUBSTATION_NO=D.SUBSTATION_NUMBER));