----------------------------------------------------------------------------/
 -- 423
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_SUB_HIER_ACLCON_SUB MINUS 
SELECT * FROM TCGACDS.GCM_SUB_HIER_ACLCON_SUB_FINAL);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('ACLCON_SUB DATA IS SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('ACLCON_SUB DATA NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
--------------------------------------------------------/
--420

SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_SUB_HIER_ACLCON_SUB_FINAL MINUS 
SELECT * FROM TCGACDS.GCM_SUB_HIER_ACLCON_SUB);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('ACLCON_SUB_FINAL DATA IS SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('ACLCON_SUB_FINAL DATA NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--418

SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM TCGACDS.GCM_V_SUB_HIER_HIGH_SIDE_CKTS;
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('HIGH_SIDE_CKTS SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('HIGH_SIDE_CKTS NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--415
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(DISTINCT FEATURE_TYPE) INTO V_COUNT  FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE BANK_TYPE='A-BANK' 
AND CHANGE_TYPE IS NOT NULL;
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('A-BANK COUNT IN GCM_v_sUB_HIER_FACILITY SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('A-BANK COUNT IN GCM_v_sUB_HIER_FACILITY NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--414
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE BANK_TYPE='A-BANK' AND CHANGE_TYPE IS NULL;
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('CHANGE_TYPE IS NULL FOR A-BANK SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('CHANGE_TYPE IS NULL FOR A-BANK NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--413
  SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
--V_FTR_TYP VARCHAR2(255 BYTE);
BEGIN 
    SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT CHANGE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE BANK_TYPE='A-BANK');
DBMS_OUTPUT.PUT_LINE( V_COUNT);
IF V_COUNT<>0
THEN
FOR REC IN(SELECT DISTINCT CHANGE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE BANK_TYPE='A-BANK')LOOP
DBMS_OUTPUT.PUT_LINE( REC.CHANGE_TYPE);

END LOOP;
ELSE
  NULL;
  END IF;
  END;
------------------------------------------------/
--412
  SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
--V_FTR_TYP VARCHAR2(255 BYTE);
BEGIN 
    SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT CHANGE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_FACILITY);
DBMS_OUTPUT.PUT_LINE( V_COUNT);
IF V_COUNT<>0
THEN
FOR REC IN(SELECT DISTINCT CHANGE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_FACILITY )LOOP
DBMS_OUTPUT.PUT_LINE( REC.CHANGE_TYPE);

END LOOP;
ELSE
  NULL;
  END IF;
  END;
------------------------------------------------/
--409
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
SELECT COUNT(DISTINCT FEATURE_TYPE) INTO V_COUNT  FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE BANK_TYPE='A-BANK' 
AND CHANGE_TYPE IS NOT NULL;
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--408
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE BANK_TYPE='A-BANK' AND CHANGE_TYPE IS NULL);
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--407
  SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
--V_FTR_TYP VARCHAR2(255 BYTE);
BEGIN 
    SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT CHANGE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_PLANNING);
DBMS_OUTPUT.PUT_LINE( V_COUNT);
IF V_COUNT<>0
THEN
FOR REC IN(SELECT DISTINCT CHANGE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_PLANNING )LOOP
DBMS_OUTPUT.PUT_LINE( REC.CHANGE_TYPE);

END LOOP;
ELSE
  NULL;
  END IF;
  END;
------------------------------------------------/
--406
  SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
--V_FTR_TYP VARCHAR2(255 BYTE);
BEGIN 
    SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT CHANGE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE BANK_TYPE='A-BANK');
DBMS_OUTPUT.PUT_LINE( V_COUNT);
IF V_COUNT<>0
THEN
FOR REC IN(SELECT DISTINCT CHANGE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE BANK_TYPE='A-BANK' )LOOP
DBMS_OUTPUT.PUT_LINE( REC.CHANGE_TYPE);

END LOOP;
ELSE
  NULL;
  END IF;
  END;
------------------------------------------------/
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE TYPE IS NULL AND NODE_tYPE<>'CIRCUIT');
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--400
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE TYPE IS NULL AND NODE_tYPE='CIRCUIT');
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--397
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE TYPE IS NULL AND NODE_tYPE<>'CIRCUIT');
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--395
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE TYPE IS NULL AND NODE_tYPE='CIRCUIT');
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--389
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE REFERENCE_SOR='MFL' AND TYPE IS NULL AND NODE_TYPE<>'CIRCUIT');
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--390
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE REFERENCE_SOR='EMS' AND TYPE IS NULL AND NODE_TYPE<>'CIRCUIT');
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--391
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE REFERENCE_SOR='GESW' AND TYPE IS NULL AND NODE_TYPE<>'CIRCUIT');
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--392
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE REFERENCE_SOR='GESW' AND TYPE IS NULL);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--393
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE REFERENCE_SOR='SAP' AND TYPE IS NULL);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--382---AS THEY DO NOT HAVE VALID VOLTAGE VALUES, BANK TYPE CANNOT BE DEFINED
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE BANK_TYPE IS NULL AND REFERENCE_SOR='SAP');
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--384
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE BANK_TYPE IS NULL AND REFERENCE_SOR<>'SAP' AND NODE_TYPE<>'CIRCUIT');
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--375
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE REFERENCE_SOR='MFL' AND TYPE IS NULL AND NODE_TYPE<>'CIRCUIT');
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--376
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE REFERENCE_SOR='EMS' AND TYPE IS NULL AND NODE_TYPE<>'CIRCUIT');
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--377
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE REFERENCE_SOR='GESW' AND TYPE IS NULL AND NODE_TYPE<>'CIRCUIT');
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--378
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE REFERENCE_SOR='GESW' AND TYPE IS NULL);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--379
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE REFERENCE_SOR='SAP' AND TYPE IS NULL);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--367
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE BANK_TYPE IS NOT NULL AND REFERENCE_SOR='SAP');
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--368
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE BANK_TYPE IS NULL AND REFERENCE_SOR='SAP' );
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--370
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE BANK_TYPE IS NULL AND REFERENCE_SOR<>'SAP' AND NODE_TYPE<>'CIRCUIT' );
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--363
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE NODE_cATEGORY='CIRCUIT' AND REFERENCE_SOR='MFL' 
AND SUB_KEY NOT LIKE '%CKT%');
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--361
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT SUB_KEY FROM TCGACDS.GCM_v_sUB_HIER_FACILITY GROUP BY SUB_KEY HAVING COUNT(*)>1);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--360
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT SUB_KEY FROM TCGACDS.GCM_v_sUB_HIER_PLANNING GROUP BY SUB_KEY HAVING COUNT(*)>1);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--359
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT CIRCUIT_ID FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE NODE_TYPE='CIRCUIT' GROUP BY CIRCUIT_ID HAVING COUNT(*)>1);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--358
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT CIRCUIT_ID FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE NODE_TYPE='CIRCUIT' GROUP BY CIRCUIT_ID HAVING COUNT(*)>1);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--356
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE NODE_TYPE='CIRCUIT'  AND (CIRCUIT_ID IS NULL OR CIRCUIT_ID='0'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--355
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE NODE_TYPE='CIRCUIT'  AND (CIRCUIT_ID IS NULL OR CIRCUIT_ID='0'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--354
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE NODE_TYPE='CIRCUIT'  AND (SUBSTATION_NO IS NOT NULL));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--336
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT MASTER_KEY FROM TCGACDS.GCM_SUB_HIER_ALL_ABANK_LIST GROUP BY MASTER_KEY HAVING COUNT(*)>1);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--338
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(select * FROM TCGACDS.GCM_SUB_HIER_ALL_ABANK_LIST WHERE ABANK_CHANGE_TYPE='LAST_UPDATED');
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--339
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(select * FROM TCGACDS.GCM_SUB_HIER_ALL_ABANK_LIST WHERE ABANK_CHANGE_TYPE IS NOT NULL );
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--340
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(select * FROM TCGACDS.GCM_SUB_HIER_ALL_ABANK_LIST WHERE ABANK_CHANGE_TYPE IS NULL);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--341
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(select * FROM TCGACDS.GCM_SUB_HIER_ALL_ABANK_LIST WHERE ABANK_SUB_KEY NOT IN 
(SELECT SUB_KEY FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE BANK_tYPE='A-BANK'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--343
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(select * FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE SUB_KEY NOT IN 
(SELECT ABANK_SUB_KEY FROM TCGACDS.GCM_SUB_HIER_ALL_ABANK_LIST) AND BANK_tYPE='A-BANK');
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--345
  SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
--V_FTR_TYP VARCHAR2(255 BYTE);
BEGIN 
    SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT ABANK_CHANGE_TYPE FROM TCGACDS.GCM_SUB_HIER_ALL_ABANK_LIST);
DBMS_OUTPUT.PUT_LINE( V_COUNT);
IF V_COUNT<>0
THEN
FOR REC IN(SELECT DISTINCT ABANK_CHANGE_TYPE FROM TCGACDS.GCM_SUB_HIER_ALL_ABANK_LIST )LOOP
DBMS_OUTPUT.PUT_LINE( REC.ABANK_CHANGE_TYPE);

END LOOP;
ELSE
  NULL;
  END IF;
  END;
------------------------------------------------/
--346
  SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
--V_FTR_TYP VARCHAR2(255 BYTE);
BEGIN 
    SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT ABANK_CHANGED_DATE FROM TCGACDS.GCM_SUB_HIER_ALL_ABANK_LIST);
DBMS_OUTPUT.PUT_LINE( V_COUNT);
IF V_COUNT<>0
THEN
FOR REC IN(SELECT DISTINCT ABANK_CHANGED_DATE FROM TCGACDS.GCM_SUB_HIER_ALL_ABANK_LIST )LOOP
DBMS_OUTPUT.PUT_LINE( REC.ABANK_CHANGED_DATE);

END LOOP;
ELSE
  NULL;
  END IF;
  END;
------------------------------------------------/
--332
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE BANK_TYPE='A-BANK' AND (ZONE IS NULL OR REGION IS NULL OR SYSTEM IS NULL 
OR ZONE_ID IS NULL OR REGION_ID IS NULL OR SYSTEM_ID IS NULL));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--334
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE BANK_TYPE='A-BANK' AND ZONE='OTHER' AND REGION='OTHER' AND SYSTEM='OTHER');
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--326
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT REFERENCE_sOR,NODE_NAME,NODE_TYPE,FTR_TYPE FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL  MINUS
SELECT REFERENCE_sOR,NODE_NAME,NODE_TYPE,FTR_TYPE FROM TCGACDS.GCM_SUB_HIER_NODE$_STG );
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--329
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT REFERENCE_sOR,NODE_NAME,NODE_TYPE,FTR_TYPE FROM TCGACDS.GCM_SUB_HIER_NODE$_STG MINUS
SELECT REFERENCE_sOR,NODE_NAME,NODE_TYPE,FTR_TYPE FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL  );
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--180
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_SUB_HIER_MFL_STG MINUS
SELECT * FROM TCGACDS.GCM_SUB_HIER_MFL_FINAL);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--183
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_SUB_HIER_MFL_FINAL MINUS
SELECT * FROM TCGACDS.GCM_SUB_HIER_MFL_STG);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--186
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT distinct gcm_sub_name FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL MINUS
SELECT distinct gcm_sub_name FROM TCGACDS.GCM_SUB_HIER_FAC_META_STG);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--189
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT distinct GCM_SUB_NAME FROM TCGACDS.GCM_SUB_HIER_FAC_META_STG MINUS
SELECT distinct GCM_SUB_NAME FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--192
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT REFERENCE_sOR,NODE_NAME,NODE_TYPE,FTR_TYPE FROM TCGACDS.GCM_SUB_HIER_NODE$_STG  MINUS
SELECT REFERENCE_sOR,NODE_NAME,NODE_TYPE,FTR_TYPE FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--195
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT REFERENCE_sOR,NODE_NAME,NODE_TYPE,FTR_TYPE FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL  MINUS
SELECT REFERENCE_sOR,NODE_NAME,NODE_TYPE,FTR_TYPE FROM TCGACDS.GCM_SUB_HIER_NODE$_STG);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT  LINK_NAME FROM TCGACDS.GCM_SUB_HIER_LINK$_FINAL MINUS
SELECT LINK_NAME FROM TCGACDS.GCM_SUB_HIER_LINK$_STG);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT  LINK_NAME FROM TCGACDS.GCM_SUB_HIER_LINK$_STG MINUS
SELECT LINK_NAME FROM TCGACDS.GCM_SUB_HIER_LINK$_FINAL);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--204-209--NODE FINAL AND VIEW COUNTS SHOULD MATCH
SET SERVEROUTPUT ON;
DECLARE 
V_NODE_COUNT NUMBER;
V_META_COUNT NUMBER;
V_PLANNING_COUNT NUMBER;
BEGIN 

SELECT COUNT(1) INTO V_NODE_COUNT FROM TCGACDS.GCM_SUB_HIER_NODE$_STG;
SELECT COUNT(1)INTO V_META_COUNT FROM TCGACDS.GCM_v_sUB_HIER_FACILITY;
SELECT COUNT(1)INTO V_PLANNING_COUNT FROM TCGACDS.GCM_v_sUB_HIER_PLANNING;

IF V_NODE_COUNT=V_META_COUNT AND V_NODE_COUNT= V_PLANNING_COUNT
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'||V_NODE_COUNT ||' | '|| V_META_COUNT ||' | '|| V_PLANNING_COUNT );
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  | '||V_NODE_COUNT||' | '|| V_META_COUNT ||' | '||V_PLANNING_COUNT );
END IF;
END;
------------------------------------------------/
--215
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--218
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL WHERE NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_v_sUB_HIER_FACILITY));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--221
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL WHERE NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_v_sUB_HIER_PLANNING));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--224
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;

------------------------------------------------/
--227
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_v_sUB_HIER_PLANNING));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--230
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_v_sUB_HIER_FACILITY));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--233
SET SERVEROUTPUT ON;
DECLARE 
V_NODE_COUNT NUMBER;
V_META_COUNT NUMBER;
V_PLANNING_COUNT NUMBER;
BEGIN   
SELECT COUNT(DISTINCT FTR_TYPE)INTO V_NODE_COUNT FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL;
SELECT COUNT(DISTINCT GCM_SUB_NAME) INTO V_META_COUNT  FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE BANK_TYPE='A-BANK';
IF V_NODE_COUNT=V_META_COUNT
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'||V_NODE_COUNT ||' | '|| V_META_COUNT  );
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  | '||V_NODE_COUNT||' | '|| V_META_COUNT);
END IF;
END;
------------------------------------------------/
--235
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT GCM_SUB_NAME FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE BANK_TYPE='A-BANK' 
AND GCM_SUB_NAME NOT IN (SELECT DISTINCT FTR_TYPE FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--237
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT FTR_TYPE FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL WHERE  FTR_TYPE NOT IN 
(SELECT DISTINCT GCM_SUB_NAME FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE BANK_TYPE='A-BANK'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--240
SET SERVEROUTPUT ON;
DECLARE 

V_META_COUNT NUMBER;
V_FTR_COUNT NUMBER;
BEGIN   
SELECT COUNT(DISTINCT FEATURE_TYPE)INTO V_FTR_COUNT FROM TCGACDS.GCM_v_sUB_HIER_FACILITY;
SELECT COUNT(DISTINCT GCM_SUB_NAME) INTO V_META_COUNT  FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE BANK_TYPE='A-BANK';
IF V_FTR_COUNT=V_META_COUNT
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'||V_FTR_COUNT ||' | '|| V_META_COUNT  );
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  | '||V_FTR_COUNT||' | '|| V_META_COUNT);
END IF;
END;
------------------------------------------------/
--242
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT GCM_SUB_NAME FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE BANK_TYPE='A-BANK' 
AND GCM_SUB_NAME NOT IN (SELECT DISTINCT FEATURE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_FACILITY));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--244
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT FEATURE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE  FEATURE_TYPE NOT IN 
(SELECT DISTINCT GCM_SUB_NAME FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE BANK_TYPE='A-BANK'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--247
SET SERVEROUTPUT ON;
DECLARE 

V_META_COUNT NUMBER;
V_FTR_COUNT NUMBER;
BEGIN   
SELECT COUNT(DISTINCT FEATURE_TYPE)INTO V_FTR_COUNT FROM TCGACDS.GCM_v_sUB_HIER_PLANNING;
SELECT COUNT(DISTINCT GCM_SUB_NAME) INTO V_META_COUNT  FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE BANK_TYPE='A-BANK';
IF V_FTR_COUNT=V_META_COUNT
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'||V_FTR_COUNT ||' | '|| V_META_COUNT  );
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  | '||V_FTR_COUNT||' | '|| V_META_COUNT);
END IF;
END;
------------------------------------------------/
--249
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT GCM_SUB_NAME FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE BANK_TYPE='A-BANK' 
AND GCM_SUB_NAME NOT IN (SELECT DISTINCT FEATURE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_PLANNING));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--251
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(SELECT DISTINCT FEATURE_TYPE FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE  FEATURE_TYPE NOT IN 
(SELECT DISTINCT GCM_SUB_NAME FROM TCGACDS.GCM_SUB_HIER_FAC_META_FINAL WHERE BANK_TYPE='A-BANK'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--254
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(
SELECT * FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL WHERE NODE_TYPE='SUBSTATION' 
AND NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE NODE_TYPE='SUBSTATION'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--258--All Dist subs populated in DISTRIBUTION level hierarchy in node table are part of view
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(
SELECT * FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL WHERE NODE_TYPE='DISTRIBUTION' 
AND NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE NODE_TYPE='DISTRIBUTION'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--263 All FEEDERS populated in FEEDER level hierarchy in node table are part of view
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(
SELECT * FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL WHERE NODE_TYPE='CIRCUIT' 
AND NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_v_sUB_HIER_PLANNING WHERE NODE_TYPE='CIRCUIT'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--268
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(
SELECT * FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL WHERE NODE_TYPE='SUBSTATION' 
AND NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE NODE_TYPE='SUBSTATION'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--272--All Dist subs populated in DISTRIBUTION level hierarchy in node table are part of view
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(
SELECT * FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL WHERE NODE_TYPE='DISTRIBUTION' 
AND NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE NODE_TYPE='DISTRIBUTION'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;

------------------------------------------------/
--277--All FEEDERS populated in FEEDER level hierarchy in node table are part of view
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(
SELECT * FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL WHERE NODE_TYPE='CIRCUIT' 
AND NODE_NAME NOT IN 
(SELECT NODE_NAME FROM TCGACDS.GCM_v_sUB_HIER_FACILITY WHERE NODE_TYPE='CIRCUIT'));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--283--DISCONNECTED GRAPH VALIDATION
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(
SELECT * FROM TCGACDS.GCM_SUB_HIER_LINK$_FINAL WHERE START_NODE_ID NOT IN (SELECT DISTINCT END_NODE_ID FROM TCGACDS.GCM_SUB_HIER_LINK$_FINAL) AND 
START_NODE_ID NOT IN (SELECT DISTINCT NODE_ID FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL
WHERE NODE_NAME = FTR_TYPE));
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--287 REPEATED NODES
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(
SELECT COUNT(NODE_ID), NODE_ID FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL
WHERE NODE_TYPE IN ('SUBSTATION','DISTRIBUTION','CIRCUIT')
GROUP BY NODE_ID HAVING COUNT(NODE_ID)>1);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--292 REPEATED NODES
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(
SELECT COUNT(NODE_NAME), NODE_NAME FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL
WHERE NODE_TYPE IN ('SUBSTATION','DISTRIBUTION')
GROUP BY NODE_NAME HAVING COUNT(NODE_NAME)>1);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--296 -NO MULTIPLE PARENT TO CHILD SCENARIO EXISTS
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN 
SELECT COUNT(*) INTO V_COUNT FROM(
SELECT COUNT(START_NODE_ID),END_NODE_ID FROM TCGACDS.GCM_SUB_HIER_LINK$_FINAL
GROUP BY END_NODE_ID HAVING COUNT(START_NODE_ID)>1);
IF V_COUNT=0
THEN 
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE  |'|| V_COUNT);
END IF;
END;
------------------------------------------------/
--167
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT NODE_ID FROM (
SELECT DISTINCT START_NODE_ID AS NODE_ID FROM TCGACDS.GCM_SUB_HIER_LINK$_FINAL
UNION
SELECT DISTINCT END_NODE_ID AS NODE_ID FROM TCGACDS.GCM_SUB_HIER_LINK$_FINAL
) WHERE NODE_ID NOT IN (SELECT NODE_ID FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL));
 IF V_COUNT =0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--163
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT NODE_KEY FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL GROUP BY NODE_KEY HAVING COUNT(*)>1);
 IF V_COUNT =0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;
------------------------------------------------/
--173
SET SERVEROUTPUT ON;
DECLARE 
V_COUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_COUNT FROM(SELECT * FROM TCGACDS.GCM_SUB_HIER_NODE$_FINAL WHERE NODE_ID NOT IN 
(
SELECT DISTINCT START_NODE_ID AS NODE_ID FROM TCGACDS.GCM_SUB_HIER_LINK$_FINAL
UNION
SELECT DISTINCT END_NODE_ID AS NODE_ID FROM TCGACDS.GCM_SUB_HIER_LINK$_FINAL
));
 IF V_COUNT <>0
 THEN
DBMS_OUTPUT.PUT_LINE('SUCCESSFUL |'|| V_COUNT);
ELSE 
DBMS_OUTPUT.PUT_LINE('NEED TO VALIDATE |'|| V_COUNT); 
END IF;
END;