-- This report validates Production M2S status ODS VS GCM VS SAP ISU
-- Last Modified date: 4/19/2023
----------------------------------------------------------------------------------------------

column Category heading "Category" Format a51
column COUNT heading "COUNT" Format a9
column Comments heading "Comment" Format a10
----circuit having transformer and unit with re-installed status (removed and instaleld)

SELECT '1.Total Inbound ISVC' as category, TOTAL_INBOUND_ISVC as count,'Info' as Comments 
FROM(
	
		SELECT
		TRUNC(SYSDATE-1) 
		AS TRANS_DATE,--Provides the report creation date

		(SELECT COUNT (DISTINCT ISVC_NUM) FROM
           (
			SELECT A.ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1) 
			and TABLE_NAME ='ODS030_METER_DTLS'
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM  FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
			AND A.OPERATION IN('INSERT','UPDATE')
			AND TABLE_NAME IN('IBANK','UG_TRANSFORMER','OH_TRANSFORMER','GROUND_BANK')
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND NVL(A.TRANSFORMER_ID_OLD,0)=NVL(G.TRANSFORMER_ID,0)
			AND A.OPERATION IN('DELETE')
			AND TABLE_NAME IN('IBANK','UG_TRANSFORMER','OH_TRANSFORMER','GROUND_BANK')
			UNION    
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND A.STRUCTURE_NO_NEW = G.STRUCT_NO
			AND A.OPERATION IN('UPDATE')
			AND TABLE_NAME IN('STRUCTURE')
           )
		)
		AS TOTAL_INBOUND_ISVC,--Provides the total count of new isvc inserted and isvc changing transformer/circuit/structure/structure type
		
		(SELECT COUNT(DISTINCT ISVC_NUM) FROM  
		   (
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count for new meter insertion on ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='INSERT'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))--GCM impact only when the isvc is not existing in M2S.Exclude ISVC records already part of GCM
            AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records
			UNION 
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count when there is change in ISVC-transformer/structure relation for a meter in ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='UPDATE' 
			AND MAPPER_ACTION_FLAG_NEW<>'REMOVE'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND A.ISVC_NUM_NEW = A.ISVC_NUM_OLD
			AND ( NVL(A.TRANSFORMER_ID_NEW,0) <>  NVL(A.TRANSFORMER_ID_OLD,0) OR NVL(A.STRUCTURE_NO_NEW,0)<> NVL(A.STRUCTURE_NO_OLD,0))--Checking if there is change on transformer/structure
			AND  EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC )
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND NVL(A.STRUCTURE_NO_NEW,0)=NVL(G.STRUCT_NO,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))
           AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records                
			UNION
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count when there is change in ISVC itself for meter in ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='UPDATE' 
			AND MAPPER_ACTION_FLAG_NEW<>'REMOVE'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND A.ISVC_NUM_NEW <> A.ISVC_NUM_OLD
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND  NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))--GCM impact only when the isvc is not existing in M2S.Exclude ISVC records already part of GCM
           AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records               
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A , TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-circuit relationship(When a transfomer is inserted/updated from GESW tables)
			WHERE NVL(A.TRANSFORMER_ID_NEW,0) = NVL(G.TRANSFORMER_ID,0)
			AND A.TABLE_NAME IN ('IBANK','OH_TRANSFORMER','UG_TRANSFORMER','GROUND_BANK') 
			AND A.OPERATION IN('INSERT','UPDATE')
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE) = TRUNC(SYSDATE-1)
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 
						    WHERE  NVL(G.TRANSFORMER_ID,0) = NVL(G1.TRANSFORMER_ID,0) 
						    AND NVL(G1.CIRCUIT_NAME,0) =  NVL(A.CIRCUIT_NAME_NEW,0)
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1))         
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A , TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-circuit relationship(When a transfomer is deleted from GESW tables)
			WHERE NVL(A.TRANSFORMER_ID_OLD,0) = NVL(G.TRANSFORMER_ID,0)
			AND A.TABLE_NAME IN ('IBANK','OH_TRANSFORMER','UG_TRANSFORMER','GROUND_BANK') 
			AND A.OPERATION IN('DELETE')
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE) = TRUNC(SYSDATE-1)
			AND NOT EXISTS(SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 
						   WHERE  NVL(G.TRANSFORMER_ID,0) = NVL(G1.TRANSFORMER_ID,0) 
						   AND G.CIRCUIT_NAME IS  NULL
                           AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1))                
            UNION		
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A ,TCGACDS.GCM_M2S_ASSOCIATION G ,TCGACDS.GCM_V_M2G_STR_DETAILS STR--Provides the GCM impacted ISVC count when there is change in ISVC-Structure Type(When a structure changes its type(strcture operation:insert,update))
			WHERE A.STRUCTURE_NO_NEW = G.STRUCT_NO
            AND G.STRUCT_NO = STR.STRUCTURE_NUMBER
			AND A.TABLE_NAME IN ('STRUCTURE') 
			AND A.OPERATION IN('UPDATE')
			AND TRUNC(EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE)=TRUNC(SYSDATE-1)
            AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1,TCGACDS.GCM_V_M2G_STR_DETAILS STR1 
							WHERE G.STRUCT_NO=G1.STRUCT_NO
                            AND G1.STRUCT_NO = STR1.STRUCTURE_NUMBER 
                            AND NVL(G1.STRUCT_TYPE,0)= NVL(STR1.FEATURE_NAME,0)
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1)
                            )             
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A ,TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-Structure Type(When a structure changes its type(strcture operation:delete))
			WHERE A.STRUCTURE_NO_NEW = G.STRUCT_NO
			AND A.TABLE_NAME IN ('STRUCTURE') 
			AND A.OPERATION IN('UPDATE')
			AND TRUNC(EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE)=TRUNC(SYSDATE-1)
            AND NOT EXISTS(SELECT 1 FROM TCGACDS.GCM_V_M2G_STR_DETAILS STR WHERE NVL(G.STRUCT_TYPE,0)= NVL(STR.FEATURE_NAME,0))
            AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 WHERE G.STRUCT_NO=G1.STRUCT_NO
                            AND G1.STRUCT_TYPE IS NULL
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1)
                            )            
            )
		)  
		AS M2S_TRACKED_CHANGES, --Provides the expected count of GCM impacted isvc

		(SELECT COUNT(DISTINCT DEVICE_LOC_ISVC ) FROM TCGACDS.GCM_M2S_ASSOCIATION 
		 WHERE TRUNC(EFFECTIVE_DTTM)=TRUNC(SYSDATE-1)) 
		AS GCM_M2S_OUTBOUND --Provides the actual count of GCM impacted isvc 
		
		FROM DUAL
    )
    
UNION

SELECT '2.Total NO_M2S_TRACKED_CHANGES' as category, TOTAL_INBOUND_ISVC-M2S_TRACKED_CHANGES as count,'Info' as Comments 
FROM(
	
		SELECT
		TRUNC(SYSDATE-1) 
		AS TRANS_DATE,--Provides the report creation date

		(SELECT COUNT (DISTINCT ISVC_NUM) FROM
           (
			SELECT A.ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1) 
			and TABLE_NAME ='ODS030_METER_DTLS'
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM  FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
			AND A.OPERATION IN('INSERT','UPDATE')
			AND TABLE_NAME IN('IBANK','UG_TRANSFORMER','OH_TRANSFORMER','GROUND_BANK')
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND NVL(A.TRANSFORMER_ID_OLD,0)=NVL(G.TRANSFORMER_ID,0)
			AND A.OPERATION IN('DELETE')
			AND TABLE_NAME IN('IBANK','UG_TRANSFORMER','OH_TRANSFORMER','GROUND_BANK')
			UNION    
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND A.STRUCTURE_NO_NEW = G.STRUCT_NO
			AND A.OPERATION IN('UPDATE')
			AND TABLE_NAME IN('STRUCTURE')
           )
		)
		AS TOTAL_INBOUND_ISVC,--Provides the total count of new isvc inserted and isvc changing transformer/circuit/structure/structure type
		
		(SELECT COUNT(DISTINCT ISVC_NUM) FROM  
		   (
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count for new meter insertion on ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='INSERT'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))--GCM impact only when the isvc is not existing in M2S.Exclude ISVC records already part of GCM
            AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records
			UNION 
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count when there is change in ISVC-transformer/structure relation for a meter in ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='UPDATE' 
			AND MAPPER_ACTION_FLAG_NEW<>'REMOVE'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND A.ISVC_NUM_NEW = A.ISVC_NUM_OLD
			AND ( NVL(A.TRANSFORMER_ID_NEW,0) <>  NVL(A.TRANSFORMER_ID_OLD,0) OR NVL(A.STRUCTURE_NO_NEW,0)<> NVL(A.STRUCTURE_NO_OLD,0))--Checking if there is change on transformer/structure
			AND  EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC )
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND NVL(A.STRUCTURE_NO_NEW,0)=NVL(G.STRUCT_NO,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))
           AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records                
			UNION
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count when there is change in ISVC itself for meter in ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='UPDATE' 
			AND MAPPER_ACTION_FLAG_NEW<>'REMOVE'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND A.ISVC_NUM_NEW <> A.ISVC_NUM_OLD
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND  NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))--GCM impact only when the isvc is not existing in M2S.Exclude ISVC records already part of GCM
           AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records               
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A , TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-circuit relationship(When a transfomer is inserted/updated from GESW tables)
			WHERE NVL(A.TRANSFORMER_ID_NEW,0) = NVL(G.TRANSFORMER_ID,0)
			AND A.TABLE_NAME IN ('IBANK','OH_TRANSFORMER','UG_TRANSFORMER','GROUND_BANK') 
			AND A.OPERATION IN('INSERT','UPDATE')
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE) = TRUNC(SYSDATE-1)
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 
						    WHERE  NVL(G.TRANSFORMER_ID,0) = NVL(G1.TRANSFORMER_ID,0) 
						    AND NVL(G1.CIRCUIT_NAME,0) =  NVL(A.CIRCUIT_NAME_NEW,0)
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1))         
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A , TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-circuit relationship(When a transfomer is deleted from GESW tables)
			WHERE NVL(A.TRANSFORMER_ID_OLD,0) = NVL(G.TRANSFORMER_ID,0)
			AND A.TABLE_NAME IN ('IBANK','OH_TRANSFORMER','UG_TRANSFORMER','GROUND_BANK') 
			AND A.OPERATION IN('DELETE')
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE) = TRUNC(SYSDATE-1)
			AND NOT EXISTS(SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 
						   WHERE  NVL(G.TRANSFORMER_ID,0) = NVL(G1.TRANSFORMER_ID,0) 
						   AND G.CIRCUIT_NAME IS  NULL
                           AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1))                
            UNION		
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A ,TCGACDS.GCM_M2S_ASSOCIATION G ,TCGACDS.GCM_V_M2G_STR_DETAILS STR--Provides the GCM impacted ISVC count when there is change in ISVC-Structure Type(When a structure changes its type(strcture operation:insert,update))
			WHERE A.STRUCTURE_NO_NEW = G.STRUCT_NO
            AND G.STRUCT_NO = STR.STRUCTURE_NUMBER
			AND A.TABLE_NAME IN ('STRUCTURE') 
			AND A.OPERATION IN('UPDATE')
			AND TRUNC(EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE)=TRUNC(SYSDATE-1)
            AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1,TCGACDS.GCM_V_M2G_STR_DETAILS STR1 
							WHERE G.STRUCT_NO=G1.STRUCT_NO
                            AND G1.STRUCT_NO = STR1.STRUCTURE_NUMBER 
                            AND NVL(G1.STRUCT_TYPE,0)= NVL(STR1.FEATURE_NAME,0)
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1)
                            )             
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A ,TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-Structure Type(When a structure changes its type(strcture operation:delete))
			WHERE A.STRUCTURE_NO_NEW = G.STRUCT_NO
			AND A.TABLE_NAME IN ('STRUCTURE') 
			AND A.OPERATION IN('UPDATE')
			AND TRUNC(EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE)=TRUNC(SYSDATE-1)
            AND NOT EXISTS(SELECT 1 FROM TCGACDS.GCM_V_M2G_STR_DETAILS STR WHERE NVL(G.STRUCT_TYPE,0)= NVL(STR.FEATURE_NAME,0))
            AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 WHERE G.STRUCT_NO=G1.STRUCT_NO
                            AND G1.STRUCT_TYPE IS NULL
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1)
                            )            
            )
		)  
		AS M2S_TRACKED_CHANGES, --Provides the expected count of GCM impacted isvc

		(SELECT COUNT(DISTINCT DEVICE_LOC_ISVC ) FROM TCGACDS.GCM_M2S_ASSOCIATION 
		 WHERE TRUNC(EFFECTIVE_DTTM)=TRUNC(SYSDATE-1)) 
		AS GCM_M2S_OUTBOUND --Provides the actual count of GCM impacted isvc 
		
		FROM DUAL
    )
    
UNION

SELECT '3.Total M2S_TRACKED_CHANGES' as category, M2S_TRACKED_CHANGES as count,'Info' as Comments 
FROM(
	
		SELECT
		TRUNC(SYSDATE-1) 
		AS TRANS_DATE,--Provides the report creation date

		(SELECT COUNT (DISTINCT ISVC_NUM) FROM
           (
			SELECT A.ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1) 
			and TABLE_NAME ='ODS030_METER_DTLS'
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM  FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
			AND A.OPERATION IN('INSERT','UPDATE')
			AND TABLE_NAME IN('IBANK','UG_TRANSFORMER','OH_TRANSFORMER','GROUND_BANK')
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND NVL(A.TRANSFORMER_ID_OLD,0)=NVL(G.TRANSFORMER_ID,0)
			AND A.OPERATION IN('DELETE')
			AND TABLE_NAME IN('IBANK','UG_TRANSFORMER','OH_TRANSFORMER','GROUND_BANK')
			UNION    
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND A.STRUCTURE_NO_NEW = G.STRUCT_NO
			AND A.OPERATION IN('UPDATE')
			AND TABLE_NAME IN('STRUCTURE')
           )
		)
		AS TOTAL_INBOUND_ISVC,--Provides the total count of new isvc inserted and isvc changing transformer/circuit/structure/structure type
		
		(SELECT COUNT(DISTINCT ISVC_NUM) FROM  
		   (
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count for new meter insertion on ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='INSERT'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))--GCM impact only when the isvc is not existing in M2S.Exclude ISVC records already part of GCM
            AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records
			UNION 
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count when there is change in ISVC-transformer/structure relation for a meter in ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='UPDATE' 
			AND MAPPER_ACTION_FLAG_NEW<>'REMOVE'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND A.ISVC_NUM_NEW = A.ISVC_NUM_OLD
			AND ( NVL(A.TRANSFORMER_ID_NEW,0) <>  NVL(A.TRANSFORMER_ID_OLD,0) OR NVL(A.STRUCTURE_NO_NEW,0)<> NVL(A.STRUCTURE_NO_OLD,0))--Checking if there is change on transformer/structure
			AND  EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC )
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND NVL(A.STRUCTURE_NO_NEW,0)=NVL(G.STRUCT_NO,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))
           AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records                
			UNION
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count when there is change in ISVC itself for meter in ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='UPDATE' 
			AND MAPPER_ACTION_FLAG_NEW<>'REMOVE'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND A.ISVC_NUM_NEW <> A.ISVC_NUM_OLD
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND  NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))--GCM impact only when the isvc is not existing in M2S.Exclude ISVC records already part of GCM
           AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records               
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A , TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-circuit relationship(When a transfomer is inserted/updated from GESW tables)
			WHERE NVL(A.TRANSFORMER_ID_NEW,0) = NVL(G.TRANSFORMER_ID,0)
			AND A.TABLE_NAME IN ('IBANK','OH_TRANSFORMER','UG_TRANSFORMER','GROUND_BANK') 
			AND A.OPERATION IN('INSERT','UPDATE')
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE) = TRUNC(SYSDATE-1)
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 
						    WHERE  NVL(G.TRANSFORMER_ID,0) = NVL(G1.TRANSFORMER_ID,0) 
						    AND NVL(G1.CIRCUIT_NAME,0) =  NVL(A.CIRCUIT_NAME_NEW,0)
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1))         
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A , TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-circuit relationship(When a transfomer is deleted from GESW tables)
			WHERE NVL(A.TRANSFORMER_ID_OLD,0) = NVL(G.TRANSFORMER_ID,0)
			AND A.TABLE_NAME IN ('IBANK','OH_TRANSFORMER','UG_TRANSFORMER','GROUND_BANK') 
			AND A.OPERATION IN('DELETE')
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE) = TRUNC(SYSDATE-1)
			AND NOT EXISTS(SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 
						   WHERE  NVL(G.TRANSFORMER_ID,0) = NVL(G1.TRANSFORMER_ID,0) 
						   AND G.CIRCUIT_NAME IS  NULL
                           AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1))                
            UNION		
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A ,TCGACDS.GCM_M2S_ASSOCIATION G ,TCGACDS.GCM_V_M2G_STR_DETAILS STR--Provides the GCM impacted ISVC count when there is change in ISVC-Structure Type(When a structure changes its type(strcture operation:insert,update))
			WHERE A.STRUCTURE_NO_NEW = G.STRUCT_NO
            AND G.STRUCT_NO = STR.STRUCTURE_NUMBER
			AND A.TABLE_NAME IN ('STRUCTURE') 
			AND A.OPERATION IN('UPDATE')
			AND TRUNC(EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE)=TRUNC(SYSDATE-1)
            AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1,TCGACDS.GCM_V_M2G_STR_DETAILS STR1 
							WHERE G.STRUCT_NO=G1.STRUCT_NO
                            AND G1.STRUCT_NO = STR1.STRUCTURE_NUMBER 
                            AND NVL(G1.STRUCT_TYPE,0)= NVL(STR1.FEATURE_NAME,0)
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1)
                            )             
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A ,TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-Structure Type(When a structure changes its type(strcture operation:delete))
			WHERE A.STRUCTURE_NO_NEW = G.STRUCT_NO
			AND A.TABLE_NAME IN ('STRUCTURE') 
			AND A.OPERATION IN('UPDATE')
			AND TRUNC(EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE)=TRUNC(SYSDATE-1)
            AND NOT EXISTS(SELECT 1 FROM TCGACDS.GCM_V_M2G_STR_DETAILS STR WHERE NVL(G.STRUCT_TYPE,0)= NVL(STR.FEATURE_NAME,0))
            AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 WHERE G.STRUCT_NO=G1.STRUCT_NO
                            AND G1.STRUCT_TYPE IS NULL
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1)
                            )            
            )
		)  
		AS M2S_TRACKED_CHANGES, --Provides the expected count of GCM impacted isvc

		(SELECT COUNT(DISTINCT DEVICE_LOC_ISVC ) FROM TCGACDS.GCM_M2S_ASSOCIATION 
		 WHERE TRUNC(EFFECTIVE_DTTM)=TRUNC(SYSDATE-1)) 
		AS GCM_M2S_OUTBOUND --Provides the actual count of GCM impacted isvc 
		
		FROM DUAL
    )
    
UNION

SELECT '4.Total GCM_M2S_OUTBOUND' as category, GCM_M2S_OUTBOUND as count,'Info' as Comments 
FROM(
	
		SELECT
		TRUNC(SYSDATE-1) 
		AS TRANS_DATE,--Provides the report creation date

		(SELECT COUNT (DISTINCT ISVC_NUM) FROM
           (
			SELECT A.ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1) 
			and TABLE_NAME ='ODS030_METER_DTLS'
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM  FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
			AND A.OPERATION IN('INSERT','UPDATE')
			AND TABLE_NAME IN('IBANK','UG_TRANSFORMER','OH_TRANSFORMER','GROUND_BANK')
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND NVL(A.TRANSFORMER_ID_OLD,0)=NVL(G.TRANSFORMER_ID,0)
			AND A.OPERATION IN('DELETE')
			AND TABLE_NAME IN('IBANK','UG_TRANSFORMER','OH_TRANSFORMER','GROUND_BANK')
			UNION    
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A,TCGACDS.GCM_M2S_ASSOCIATION G 
			WHERE TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND A.STRUCTURE_NO_NEW = G.STRUCT_NO
			AND A.OPERATION IN('UPDATE')
			AND TABLE_NAME IN('STRUCTURE')
           )
		)
		AS TOTAL_INBOUND_ISVC,--Provides the total count of new isvc inserted and isvc changing transformer/circuit/structure/structure type
		
		(SELECT COUNT(DISTINCT ISVC_NUM) FROM  
		   (
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count for new meter insertion on ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='INSERT'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))--GCM impact only when the isvc is not existing in M2S.Exclude ISVC records already part of GCM
            AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records
			UNION 
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count when there is change in ISVC-transformer/structure relation for a meter in ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='UPDATE' 
			AND MAPPER_ACTION_FLAG_NEW<>'REMOVE'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND A.ISVC_NUM_NEW = A.ISVC_NUM_OLD
			AND ( NVL(A.TRANSFORMER_ID_NEW,0) <>  NVL(A.TRANSFORMER_ID_OLD,0) OR NVL(A.STRUCTURE_NO_NEW,0)<> NVL(A.STRUCTURE_NO_OLD,0))--Checking if there is change on transformer/structure
			AND  EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC )
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND NVL(A.STRUCTURE_NO_NEW,0)=NVL(G.STRUCT_NO,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))
           AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records                
			UNION
			SELECT ISVC_NUM_NEW AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A--Provides the GCM impacted isvc count when there is change in ISVC itself for meter in ods030_meter_dtls
			WHERE TABLE_NAME='ODS030_METER_DTLS' 
			AND OPERATION='UPDATE' 
			AND MAPPER_ACTION_FLAG_NEW<>'REMOVE'
			AND TRUNC(OPERATION_DATE)=TRUNC(SYSDATE-1)
			AND A.ISVC_NUM_NEW <> A.ISVC_NUM_OLD
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G 
							WHERE A.ISVC_NUM_NEW=G.DEVICE_LOC_ISVC 
							AND  NVL(A.TRANSFORMER_ID_NEW,0)=NVL(G.TRANSFORMER_ID,0)
							AND TRUNC(EFFECTIVE_DTTM)<TRUNC(SYSDATE-1))--GCM impact only when the isvc is not existing in M2S.Exclude ISVC records already part of GCM
           AND EXISTS (SELECT 1 FROM TCGACDS.ODS030_METER_DTLS O
                        WHERE A.ISVC_NUM_NEW = O.ISVC_NUM
                        AND MAPPER_ACTION_FLAG <> 'REMOVE')--To consider only the active records               
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A , TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-circuit relationship(When a transfomer is inserted/updated from GESW tables)
			WHERE NVL(A.TRANSFORMER_ID_NEW,0) = NVL(G.TRANSFORMER_ID,0)
			AND A.TABLE_NAME IN ('IBANK','OH_TRANSFORMER','UG_TRANSFORMER','GROUND_BANK') 
			AND A.OPERATION IN('INSERT','UPDATE')
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE) = TRUNC(SYSDATE-1)
			AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 
						    WHERE  NVL(G.TRANSFORMER_ID,0) = NVL(G1.TRANSFORMER_ID,0) 
						    AND NVL(G1.CIRCUIT_NAME,0) =  NVL(A.CIRCUIT_NAME_NEW,0)
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1))         
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A , TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-circuit relationship(When a transfomer is deleted from GESW tables)
			WHERE NVL(A.TRANSFORMER_ID_OLD,0) = NVL(G.TRANSFORMER_ID,0)
			AND A.TABLE_NAME IN ('IBANK','OH_TRANSFORMER','UG_TRANSFORMER','GROUND_BANK') 
			AND A.OPERATION IN('DELETE')
			AND TRUNC(G.EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE) = TRUNC(SYSDATE-1)
			AND NOT EXISTS(SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 
						   WHERE  NVL(G.TRANSFORMER_ID,0) = NVL(G1.TRANSFORMER_ID,0) 
						   AND G.CIRCUIT_NAME IS  NULL
                           AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1))                
            UNION		
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A ,TCGACDS.GCM_M2S_ASSOCIATION G ,TCGACDS.GCM_V_M2G_STR_DETAILS STR--Provides the GCM impacted ISVC count when there is change in ISVC-Structure Type(When a structure changes its type(strcture operation:insert,update))
			WHERE A.STRUCTURE_NO_NEW = G.STRUCT_NO
            AND G.STRUCT_NO = STR.STRUCTURE_NUMBER
			AND A.TABLE_NAME IN ('STRUCTURE') 
			AND A.OPERATION IN('UPDATE')
			AND TRUNC(EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE)=TRUNC(SYSDATE-1)
            AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1,TCGACDS.GCM_V_M2G_STR_DETAILS STR1 
							WHERE G.STRUCT_NO=G1.STRUCT_NO
                            AND G1.STRUCT_NO = STR1.STRUCTURE_NUMBER 
                            AND NVL(G1.STRUCT_TYPE,0)= NVL(STR1.FEATURE_NAME,0)
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1)
                            )             
			UNION
			SELECT G.DEVICE_LOC_ISVC AS ISVC_NUM FROM TCGACDS.GCM_M2S_AUDIT A ,TCGACDS.GCM_M2S_ASSOCIATION G--Provides the GCM impacted ISVC count when there is change in ISVC-Structure Type(When a structure changes its type(strcture operation:delete))
			WHERE A.STRUCTURE_NO_NEW = G.STRUCT_NO
			AND A.TABLE_NAME IN ('STRUCTURE') 
			AND A.OPERATION IN('UPDATE')
			AND TRUNC(EFFECTIVE_DTTM) <= TRUNC(SYSDATE-1)
			AND TRUNC(A.OPERATION_DATE)=TRUNC(SYSDATE-1)
            AND NOT EXISTS(SELECT 1 FROM TCGACDS.GCM_V_M2G_STR_DETAILS STR WHERE NVL(G.STRUCT_TYPE,0)= NVL(STR.FEATURE_NAME,0))
            AND NOT EXISTS (SELECT 1 FROM TCGACDS.GCM_M2S_ASSOCIATION G1 WHERE G.STRUCT_NO=G1.STRUCT_NO
                            AND G1.STRUCT_TYPE IS NULL
                            AND TRUNC(G1.EFFECTIVE_DTTM) < TRUNC(SYSDATE-1)
                            )            
            )
		)  
		AS M2S_TRACKED_CHANGES, --Provides the expected count of GCM impacted isvc

		(SELECT COUNT(DISTINCT DEVICE_LOC_ISVC ) FROM TCGACDS.GCM_M2S_ASSOCIATION 
		 WHERE TRUNC(EFFECTIVE_DTTM)=TRUNC(SYSDATE-1)) 
		AS GCM_M2S_OUTBOUND --Provides the actual count of GCM impacted isvc 
		
		FROM DUAL
    );