column RunDate heading "RunDate" Format a9
column CIRCUIT_NAME heading "CIRCUIT_NAME" Format a10
column VALIDATION_TYPE heading "VALIDATION_TYPE" Format a29
column FEATURE_NAME heading "FEATURE_NAME" Format a18
column COUNT heading "COUNT" Format a5
-----------------------------------

SELECT DISTINCT RunDate, CIRCUIT_NAME, SUBSTR(VALIDATION_TYPE,1,32) as VALIDATION_TYPE, SUBSTR(FEATURE_NAME,1,18) as FEATURE_NAME , COUNT FROM 
(
select to_char(RAPTOR_RUN_DATE, 'YYMMDD')as RunDate, CIRCUIT_NAME, VALIDATION_TYPE,FEATURE_NAME,  
COUNT(*) as COUNT from TCGACDS.GCM_RAPTOR_LOG_ANALYSIS_CKT 
WHERE STATUS ='FAIL' and to_char(RAPTOR_RUN_DATE, 'YYMMDD') IN ( 

select RunDate from ( 
select to_char(RAPTOR_RUN_DATE,'YYMMDD') as RunDate , RANK() over (order by to_char(RAPTOR_RUN_DATE, 'YYMMDD') DESC) 
as RNK from  TCGACDS.GCM_RAPTOR_LOGS GROUP BY to_char(RAPTOR_RUN_DATE,'YYMMDD')
) where RNK=1 )

GROUP BY to_char(RAPTOR_RUN_DATE, 'YYMMDD'), CIRCUIT_NAME, VALIDATION_TYPE,FEATURE_NAME
ORDER BY CIRCUIT_NAME, RunDate, VALIDATION_TYPE, STATUS, FEATURE_NAME DESC);


----SELECT * FROM TCGACDS.GCM_RAPTOR_LOG_ANALYSIS_CKT ORDER BY RAPTOR_RUN_DATE ASC