--This report validate report validates Redbook Subsattion data
-- Last Modified Date: 11/05/2021
    
--------------------------------------------------------------------------------------------------

column Category heading "Category" Format a53
column COUNT heading "COUNT" Format a10
column Comments heading "Comments" Format a7

--Redbook data for type Substation in STG   --1595
SELECT '1.REDBOOK data count for ntwk typ Substation in stg' as Category, COUNT(*) as COUNT, 'Info' as Comments
 FROM TCGACDS.GCM_REDBOOK_STAGING WHERE NETWORK_TYPE='SUBSTATION'
UNION

--948
SELECT '1a.Count of cape substation with Redbook data' as Category, count(distinct cape_substation) as COUNT, 'Info' as Comments 
FROM TCGACDS.GCM_REDBOOK_STAGING WHERE NETWORK_TYPE='SUBSTATION'

UNION
-- Check count of duplicate Readbook subsattion data in stg
SELECT '2.Duplicate Rdbk data for ntwk typ Substation in stg' as Category, COUNT(*) as COUNT, 'Info' as Comments FROM TCGACDS.GCM_REDBOOK_STAGING WHERE NETWORK_TYPE='SUBSTATION' AND TRIM(UPPER(NETWORK_ID)) IN
(SELECT TRIM(UPPER(NETWORK_ID)) FROM TCGACDS.GCM_REDBOOK_STAGING WHERE NETWORK_TYPE='SUBSTATION' GROUP BY TRIM(UPPER(NETWORK_ID)) HAVING COUNT(1)>1  
)
UNION
--Bus unavailable in Redbook for valid EMS Substation -- 894  --957  --302(substatios)
SELECT '3.EMS Substation count missing busbar name in Redbook' as Category, count(DISTINCT GCM_SUBSTATION_ID) as COUNT, 'Info' as Comments   
FROM TCGACDS.GCM_SCIM_BUSBARSECTION WHERE GCM_JOBID=(SELECT JOBID FROM TCGACDS.GCM_PROCESS_STATUS WHERE ACTIVEJOBID='Y') AND GCM_SUBSTATION_ID IN 
(SELECT MRID FROM TCGACDS.GCM_SCIM_SUBSTATION WHERE GCM_JOBID=(SELECT JOBID FROM TCGACDS.GCM_PROCESS_STATUS WHERE ACTIVEJOBID='Y') AND TYP IS NOT NULL)
AND NAME NOT IN(SELECT DISTINCT TRIM(UPPER(NETWORK_ID)) FROM TCGACDS.GCM_REDBOOK_STAGING WHERE NETWORK_TYPE='SUBSTATION') 
UNION
--Substation unavailable in Redbook for valid GESW Substation --223 ---137
SELECT '4.All GESW Sub count missing data in Redbook' as Category, count( NAME) as COUNT, 'Info' as Comments  
FROM TCGACDS.SUBSTATION WHERE TO_NUMBER(SUBSTR(LOW_VOLTAGE,0,(LENGTH(LOW_VOLTAGE)-2)))<40 
AND TO_NUMBER(SUBSTR(HIGH_VOLTAGE,0,(LENGTH(HIGH_VOLTAGE)-2)))<40
AND UPPER(NAME) NOT IN(SELECT DISTINCT UPPER(cape_substation) FROM TCGACDS.GCM_REDBOOK_STAGING WHERE NETWORK_TYPE='SUBSTATION') 

UNION
--Substation unavailable in Redbook for GESW Substation not coming from EMS -- 78 --75
--(since GESW and EMS is matching then EMS overrides so we are checking remaining GESW which are not matching)
SELECT '4a.Only GESW Sub count missing data in Redbook' as Category, count(NAME) as COUNT, 'Info' as Comments FROM TCGACDS.SUBSTATION WHERE TO_NUMBER(SUBSTR(LOW_VOLTAGE,0,(LENGTH(LOW_VOLTAGE)-2)))<40 
AND TO_NUMBER(SUBSTR(HIGH_VOLTAGE,0,(LENGTH(HIGH_VOLTAGE)-2)))<40
AND SUBSTATION_NO NOT IN (SELECT SAP_FLOC FROM TCGACDS.EMS_SUBSTATION WHERE SAP_FLOC IS NOT NULL)
AND UPPER(NAME) NOT IN(SELECT DISTINCT UPPER(cape_substation) FROM TCGACDS.GCM_REDBOOK_STAGING WHERE NETWORK_TYPE='SUBSTATION') 
UNION
--Available in Redbook but Substation/Bus unavailable in GESW/EMS --107 --42
SELECT '5.Substation in Redbook STG but not in GESW/EMS' as Category, Count(DISTINCT TRIM(UPPER(cape_substation))) as COUNT, 'Info' as Comments  
FROM TCGACDS.GCM_REDBOOK_STAGING WHERE NETWORK_TYPE='SUBSTATION' AND UPPER(cape_substation)  NOT IN
(SELECT UPPER(SUB.NAME) FROM TCGACDS.SUBSTATION SUB WHERE TO_NUMBER(SUBSTR(LOW_VOLTAGE,0,(LENGTH(LOW_VOLTAGE)-2)))<40 AND TO_NUMBER(SUBSTR(HIGH_VOLTAGE,0,(LENGTH(HIGH_VOLTAGE)-2)))<40)
AND TRIM(UPPER(NETWORK_ID)) NOT IN (SELECT NAME FROM TCGACDS.GCM_SCIM_BUSBARSECTION WHERE GCM_JOBID=(SELECT JOBID FROM TCGACDS.GCM_PROCESS_STATUS WHERE ACTIVEJOBID='Y') AND GCM_SUBSTATION_ID IN 
(SELECT MRID FROM TCGACDS.GCM_SCIM_SUBSTATION WHERE GCM_JOBID=(SELECT JOBID FROM TCGACDS.GCM_PROCESS_STATUS WHERE ACTIVEJOBID='Y') AND TYP IS NOT NULL))
UNION
SELECT 'Validating a record got instered in the GCM_REDBOOK_EXCEL_AUDIT table'  AS Category , REC_COUNT AS COUNT,
(CASE WHEN REC_COUNT >= 1 THEN 'PASS' ELSE 'FAIL' END) AS Comments FROM (
SELECT count(*) AS REC_COUNT FROM  TCGACDS.GCM_REDBOOK_EXCEL_AUDIT 
WHERE  jobid in (SELECT max(jobid) FROM  TCGACDS.GCM_REDBOOK_EXCEL_AUDIT 
WHERE INGESTION_SUCCESSFUL ='Y'))
union
SELECT 'Validate the latest file name manually from: \\sce\workgroup\AppData\GCMR3Dev\REDBOOK ' AS Category , 
1 AS COUNT,
'Expected file name:' || FILE_NAME AS Comments FROM (
SELECT distinct FILE_NAME FROM  TCGACDS.GCM_REDBOOK_EXCEL_AUDIT 
WHERE JOBID IN (SELECT max(jobid) FROM  TCGACDS.GCM_REDBOOK_EXCEL_AUDIT 
WHERE INGESTION_SUCCESSFUL ='Y'));
