SET PAGESIZE 10000
SET FEED OFF
SET LINESIZE 160

column Validations heading "Validations" Format A120
column COUNT heading "COUNT" Format 9999999999
column Remarks heading "Remarks" Format A20

SELECT 'Validating a record got instered in the GCM_REDBOOK_AUDIT table'  AS Validations , REC_COUNT AS COUNT,
(CASE WHEN REC_COUNT >= 1 THEN 'PASS' ELSE 'FAIL' END) AS Remarks FROM (
SELECT count(*) AS REC_COUNT FROM  TCGACDS.GCM_REDBOOK_AUDIT 
WHERE  jobid in (SELECT max(jobid) FROM  TCGACDS.GCM_REDBOOK_AUDIT 
WHERE INGESTION_SUCCESSFUL ='Y'))
union
SELECT 'Total number of records loaded into GCM_REDBOOK_STAGING Table' AS Validations, 
REDBOOK_STAGING_COUNT AS COUNT,
(CASE WHEN REDBOOK_STAGING_COUNT = REDBOOK_AUDIT_TABLE_COUNT THEN 'PASS' ELSE 'FAIL' END) AS REMARKS FROM
(
SELECT
 REDBOOK_AUDIT_TABLE_COUNT,
(select count(*)  from  TCGACDS.GCM_REDBOOK_STAGING) as REDBOOK_STAGING_COUNT
from 
(SELECT SUM(RECORD_COUNT) AS REDBOOK_AUDIT_TABLE_COUNT FROM TCGACDS.GCM_REDBOOK_AUDIT
where JOBID IN (SELECT max(jobid) FROM  TCGACDS.GCM_REDBOOK_AUDIT 
WHERE INGESTION_SUCCESSFUL ='Y')))
union
SELECT 'Validate the latest file name manually from: \\sce\workgroup\AppData\GCMR3Dev\REDBOOK ' AS Validations , 
1 AS COUNT,
'Expected file name:' || FILE_NAME AS Remarks FROM (
SELECT distinct FILE_NAME FROM  TCGACDS.GCM_REDBOOK_AUDIT 
WHERE JOBID IN (SELECT max(jobid) FROM  TCGACDS.GCM_REDBOOK_AUDIT 
WHERE INGESTION_SUCCESSFUL ='Y'));