SET PAGESIZE 10000
SET FEED OFF
SET LINESIZE 160

column Validations heading "Validations" Format A120
column COUNT heading "COUNT" Format 9999999999
column Remarks heading "Remarks" Format A20

SELECT 'Circuits missing to be processed for TRANS SUBTRANS load BUFF Generation' AS VALIDATIONS, COUNT(*) AS COUNT, (CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END) AS Remarks FROM( 
SELECT DISTINCT TO_CHAR(CIRCT_ID) FROM (SELECT CKT.* FROM TCGACDS.CIRCUIT_DATA CKT
WHERE  CKT.IN_SERV_DATETIME IS NOT NULL AND CKT.OUT_SERV_DATETIME IS NULL
AND ((CIRCUIT_TYPE='S' OR CIRCUIT_TYPE='Y' OR CIRCUIT_TYPE='Z') OR (CIRCUIT_TYPE = 'F' AND DEVICE_TYPE = 'T'))
AND CIRCT_VOLT_VAL > 33  and to_char(circt_id) in(select circt_id from TCGACDS.oh_trans_conductor where route is not null
                union select circt_id from TCGACDS.ug_trans_conductor where route is not null)) 
MINUS
SELECT DISTINCT SRC_REC_ID FROM TCGACDS.GCM_BUFF_POLY WHERE BUFF_TYPE = 'CKT_C_TRAN')  
union
SELECT 'Circuits missing to be processed for TRANS SUBTRANS load' AS VALIDATIONS, COUNT(*) AS COUNT, (CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END) AS Remarks FROM 
(SELECT DISTINCT REPLACE((CIRCT_NAM),'/','-') FROM (SELECT CKT_DATA.*,
                        (CASE WHEN (CKT_DATA.CIRCT_VOLT_VAL > 33 AND CKT_DATA.CIRCT_VOLT_VAL  <= 115) THEN 'SUBTRANSMISSION'
                              WHEN (CKT_DATA.CIRCT_VOLT_VAL >= 161 AND CKT_DATA.CIRCT_VOLT_VAL  <= 500) THEN 'TRANSMISSION'
                              ELSE NULL
                        END) AS CKT_TYPE,
                        SUB.NAME AS SUBST_NAME
                FROM TCGACDS.CIRCUIT_DATA CKT_DATA
                    INNER JOIN TCGACDS.GCM_BUFF_POLY GCM_BUFF
                        ON CKT_DATA.CIRCT_NO = GCM_BUFF.BUFF_TYPE_NAME AND TO_CHAR(CKT_DATA.CIRCT_ID)=GCM_BUFF.SRC_REC_ID
                    LEFT JOIN TCGACDS.SUBSTATION SUB
                        ON CKT_DATA.SUBST_ID = SUB.SUBST_ID
                WHERE ((CKT_DATA.CIRCT_VOLT_VAL > 33 AND CKT_DATA.CIRCT_VOLT_VAL  <= 115) OR (CKT_DATA.CIRCT_VOLT_VAL >= 161 AND CKT_DATA.CIRCT_VOLT_VAL  <= 500))
                    AND CKT_DATA.CIRCT_STAT_CD IN ('I','F')
                    AND GCM_BUFF.BUFF_TYPE='CKT_C_TRAN') MINUS
                    SELECT DISTINCT CIRCUIT_NAME FROM TCGACDS.GCM_GEOSPATIAL_CIRCUIT_INFO 
					WHERE CIRCUIT_TYPE IN ('TRANSMISSION', 'SUBTRANSMISSION'))
union
SELECT 'Circuits missing to be processed for Distribution Circuit Spatial load BUFF Generation' AS VALIDATIONS, COUNT(*) AS COUNT, (CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END) AS Remarks FROM( 
WITH GEOM AS(
      SELECT circuit_name1
        FROM TCGACDS.oh_primary_conductor opc
        WHERE opc.route is not null
      UNION ALL
        SELECT circuit_name1
        FROM TCGACDS.ug_primary_conductor upc
        WHERE upc.route is not null
    ) 
                SELECT * FROM TCGACDS.CIRCUIT_DATA WHERE CIRCT_NAM IN((SELECT DISTINCT CKT.CIRCT_NAM FROM TCGACDS.CIRCUIT_DATA CKT
                WHERE  CKT.IN_SERV_DATETIME IS NOT NULL AND CKT.OUT_SERV_DATETIME IS NULL
                AND ((CIRCUIT_TYPE='A' OR CIRCUIT_TYPE='B' OR CIRCUIT_TYPE='C' OR CIRCUIT_TYPE='D' OR CIRCUIT_TYPE='G' OR CIRCUIT_TYPE='H' OR CIRCUIT_TYPE='X')
                OR (CIRCUIT_TYPE = 'F' AND DEVICE_TYPE = 'D'))
                AND CIRCT_VOLT_VAL <=33 MINUS SELECT DISTINCT BUFF_TYPE_NAME FROM TCGACDS.GCM_BUFF_POLY WHERE BUFF_TYPE='CKT_CONCAT') MINUS
                SELECT DISTINCT KEY_COL_VALUE FROM TCGACDS.GCM2020_EXCEPTION WHERE PRGM_UNIT_NAME = 'GCM_P_CKT_BUFF_GENERATION')
                AND EXISTS (SELECT 1 FROM GEOM WHERE CIRCUIT_NAME1 = CIRCT_NAM)
                AND EXISTS (SELECT 1 FROM TCGACDS.CIRCUIT_HEAD WHERE CIRCT_NAM = CIRCUIT_NAME))
				union
SELECT 'Circuits missing to be processed for Distribution Circuit Spatial load' AS VALIDATIONS, COUNT(*) AS COUNT, (CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END) AS Remarks FROM (
SELECT DISTINCT CIRCT_NAM FROM(SELECT CKT_DATA.*,
                        'DISTRIBUTION' AS CKT_TYPE,
                        SUB.NAME AS SUBST_NAME
                FROM TCGACDS.CIRCUIT_DATA CKT_DATA
                     INNER JOIN TCGACDS.GCM_BUFF_POLY GCM_BUFF
                        ON TO_CHAR(CKT_DATA.CIRCT_ID)=GCM_BUFF.SRC_REC_ID
                    LEFT JOIN TCGACDS.SUBSTATION SUB
                        ON CKT_DATA.SUBST_ID = SUB.SUBST_ID
                WHERE CKT_DATA.CIRCT_VOLT_VAL <= 33
                    AND CKT_DATA.CIRCT_STAT_CD IN ('I','F')
                    AND GCM_BUFF.BUFF_TYPE='CKT_CONCAT') MINUS SELECT DISTINCT CIRCUIT_NAME FROM TCGACDS.GCM_GEOSPATIAL_CIRCUIT_INFO WHERE CIRCUIT_TYPE = 'DISTRIBUTION');