SET PAGESIZE 10000
SET FEED OFF
SET LINESIZE 200

column CIRCUIT_NAME heading "CIRCUIT" format A20
column TOTAL_TB heading "TOTAL_TB" format 9999999
column TOTAL_TU heading "TOTAL_TU" format 99999999
column TU_MISSING_SL_NO heading "TU_MISSING_SL_NO" format 99999999
column TB_MISSING_SL_NO_FOR_ALL_UNITS heading "TB_MISSING_SL_NO_FOR_ALL_UNITS" format 99999999
column TB_WITHOUT_KVA heading "TB_WITHOUT_KVA" format 99999999
column TB_WITHOUT_USAGEPOINT heading "TB_WITHOUT_USAGEPOINT" format 99999999
column TOTAL_DISTINCT_DQ_COUNT heading "TOTAL_DISTINCT_DQ_COUNT" format 9999999
column TB_DQ_ISSUE heading "TB_DQ_ISSUE" format 999



alter session set current_schema=tcgacds;

SELECT 
CIRCUIT_NAME,
TOTAL_TB,
TOTAL_TU,
TU_MISSING_SL_NO,
TB_MISSING_SL_NO_FOR_ALL_UNITS,
TB_WITHOUT_KVA,
TB_WITHOUT_USAGEPOINT,
TOTAL_DISTINCT_DQ_COUNT,
ROUND((TOTAL_DISTINCT_DQ_COUNT/TOTAL_TB)* 100, 0) AS TB_DQ_ISSUE
FROM
(SELECT 
CIRCUIT_NAME,
TOTAL_TB,
TOTAL_TU,
TU_MISSING_SL_NO,
TB_MISSING_SL_NO_FOR_ALL_UNITS,
TB_WITHOUT_KVA,
TB_WITHOUT_USAGEPOINT,
(select count(1) from (select distinct regexp_substr (
Final_List,
'[^,]+',
1,
level
) value
from dual
connect by level <=
length ( Final_List ) - length ( replace ( Final_List, ',' ) ) + 1))  Total_Distinct_DQ_Count
FROM
(WITH 
UNIT_SLNUM_NULL AS (SELECT POWERTRANSFOMER_CIRCUITID, SUM(CASE WHEN SLNUM_NULL=PT_CNT THEN 1 ELSE 0 END) AS XFMRBANK_SL_NUM_NULL,
MAX(CASE WHEN SLNUM_NULL=PT_CNT THEN TB_LIST ELSE NULL END) AS XFMRBANK_SL_NUM_NULL_LIST
FROM (SELECT STR.POWERTRANSFOMER_CIRCUITID ,
STR.TRANSFORMERBANKIDENTIFIER_NAME AS XFMR_BANK_ID,
SUM(CASE WHEN POWERTRANSFOMERASSET_SERIALNUMBER IS NULL THEN 1 ELSE 0 END) AS SLNUM_NULL,
COUNT(DISTINCT STR.POWERTRANSFOMERIDENTIFIER_NAME) AS PT_CNT,
LISTAGG(DISTINCT STR.TRANSFORMERBANKIDENTIFIER_NAME,',') TB_LIST
FROM TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS STR
WHERE STR.POWERTRANSFOMER_STATUS_VLU <> 'REMOVED'
GROUP BY STR.POWERTRANSFOMER_CIRCUITID,STR.TRANSFORMERBANKIDENTIFIER_NAME) GROUP BY POWERTRANSFOMER_CIRCUITID),
TB_USAGEPOINT AS (SELECT S.POWERTRANSFOMER_CIRCUITID CIRCUITID, COUNT(DISTINCT S.TRANSFORMERBANKIDENTIFIER_NAME) AS TB_COUNT,LISTAGG(DISTINCT S.TRANSFORMERBANKIDENTIFIER_NAME,',') TB_COUNT_LIST
FROM GCM_SCIM_DIST_STRUCTXFM_DS  S WHERE S.POWERTRANSFOMER_STATUS_VLU <> 'REMOVED' AND
NOT EXISTS (select 1 from TCGACDS.GCM_SCIM_DIST_USAGEPOINT_DS U WHERE U.TRANSFORMERBANK_MRID =S.TRANSFORMERBANK_MRID) GROUP BY S.POWERTRANSFOMER_CIRCUITID)
SELECT 
CIRCUIT_NAME,
TOTAL_TB,
TOTAL_TU,
TU_MISSING_SL_NO,
TB_MISSING_SL_NO_FOR_ALL_UNITS,
TB_MISSING_SL_NO_FOR_ALL_UNITS_LIST,
TB_WITHOUT_KVA,
TB_WITHOUT_KVA_LIST,
TB_WITHOUT_USAGEPOINT,
TB_WITHOUT_USAGEPOINT_LIST,
(CASE when TB_MISSING_SL_NO_FOR_ALL_UNITS_LIST is not null then TB_MISSING_SL_NO_FOR_ALL_UNITS_LIST||',' else TB_MISSING_SL_NO_FOR_ALL_UNITS_LIST end)||
(CASE when TB_WITHOUT_KVA_LIST is not null then TB_WITHOUT_KVA_LIST||',' else TB_WITHOUT_KVA_LIST end)|| 
 TB_WITHOUT_USAGEPOINT_LIST  Final_List--,
/*(CASE WHEN (TB_MISSING_SL_NO_FOR_ALL_UNITS+TB_WITHOUT_KVA+TB_WITHOUT_USAGEPOINT) > = TOTAL_TB THEN 100
ELSE ROUND(((TB_MISSING_SL_NO_FOR_ALL_UNITS+TB_WITHOUT_KVA+TB_WITHOUT_USAGEPOINT)/TOTAL_TB)* 100, 0)
END) AS TB_DQ_ISSUE*/
FROM(
SELECT DS.FEEDER_CIRCUITNAME CIRCUIT_NAME,
COUNT(DISTINCT STR.TRANSFORMERBANKIDENTIFIER_NAME) TOTAL_TB,
COUNT(DISTINCT STR.POWERTRANSFOMERIDENTIFIER_NAME) TOTAL_TU,
SUM(CASE WHEN POWERTRANSFOMERASSET_SERIALNUMBER IS NULL THEN 1 ELSE 0 END) TU_MISSING_SL_NO,
MAX(X.XFMRBANK_SL_NUM_NULL) AS TB_MISSING_SL_NO_FOR_ALL_UNITS,
max(X.XFMRBANK_SL_NUM_NULL_LIST) AS TB_MISSING_SL_NO_FOR_ALL_UNITS_LIST,
SUM(CASE WHEN (DECODE(TRIM(TRANSFORMERBANK_KVASIZE),'0','0',NULL,'0','UNKNOWN','0')) = '0' THEN 1 ELSE 0 END) TB_WITHOUT_KVA,
LISTAGG(DISTINCT CASE WHEN (DECODE(TRIM(TRANSFORMERBANK_KVASIZE),'0','0',NULL,'0','UNKNOWN','0')) = '0' THEN  STR.TRANSFORMERBANKIDENTIFIER_NAME ELSE NULL END,',')TB_WITHOUT_KVA_LIST,
MAX(TB_USAGEPOINT.TB_COUNT) TB_WITHOUT_USAGEPOINT,
MAX(TB_USAGEPOINT.TB_COUNT_LIST) TB_WITHOUT_USAGEPOINT_LIST
FROM TCGACDS.GCM_SCIM_DIST_FEEDER_DS DS 
INNER JOIN TCGACDS.GCM_SCIM_DIST_STRUCTXFM_DS STR
ON DS.FEEDER_CIRCUITID=STR.POWERTRANSFOMER_CIRCUITID
AND STR.POWERTRANSFOMER_STATUS_VLU <> 'REMOVED'
INNER JOIN UNIT_SLNUM_NULL X ON X.POWERTRANSFOMER_CIRCUITID=STR.POWERTRANSFOMER_CIRCUITID
INNER JOIN TB_USAGEPOINT ON TB_USAGEPOINT.CIRCUITID=DS.FEEDER_CIRCUITID
GROUP BY FEEDER_CIRCUITNAME)));
