DECLARE
VMAX_BATCH NUMBER;
VCOUNT NUMBER:=0;
V_RCNT_M2G NUMBER:=1000;
V_RCNT_STR NUMBER:=1000;
V_RCNT_CKT NUMBER:=1000;
V_RCNT_DRDM NUMBER:=20000;
VMAXID NUMBER;
BEGIN

SELECT MAX(ID) INTO VMAXID FROM TCGACDS.SWSYNC_TRANSACTION;

--insert transaction for m2g
FOR REC IN (SELECT ID,'OH_TRANSFORMER' AS TABLE_NAME,'UPDATE' AS OPERATION,801201912 AS JOBID, SYSTIMESTAMP AS TRANS_DATE,SYSTIMESTAMP  AS SYNC_DATE,SYSTIMESTAMP AS PROCESS_DATE,CIRCUIT_NAME1,NULL AS CIRCUIT_NAME2,STRUCTURE_NUMBER,M3I_OBJECT_ID FROM TCGACDS.OH_TRANSFORMER 
WHERE ROWNUM<V_RCNT_M2G
UNION ALL
SELECT ID,'OH_PRIMARY_CONDUCTOR' AS TABLE_NAME,'UPDATE' AS OPERATION,801201912  AS JOBID,SYSTIMESTAMP AS TRANS_DATE,SYSTIMESTAMP AS SYNC_DATE,SYSTIMESTAMP AS PROCESS_DATE,CIRCUIT_NAME1,NULL AS CIRCUIT_NAME2,NULL AS STRUCTURE_NUMBER,M3I_OBJECT_ID FROM TCGACDS.OH_PRIMARY_CONDUCTOR 
WHERE ROWNUM<V_RCNT_STR)LOOP
VCOUNT:=VCOUNT+1;
Insert into TCGACDS.SWSYNC_TRANSACTION (RECORD_ID,TABLE_NAME,OPERATION,JOBID,TRANS_DATE,SYNC_DATE,PROCESS_DATE,CIRCUIT_NAME1,CIRCUIT_NAME2,STRUCTURE_NUMBER,M3I_OBJECT_ID,ID,CIRCUIT_NAME3,TLM_UPDATE) 
VALUES(REC.ID,REC.TABLE_NAME,REC.OPERATION,REC.JOBID,REC.TRANS_DATE,REC.SYNC_DATE,REC.PROCESS_DATE,REC.CIRCUIT_NAME1,REC.CIRCUIT_NAME2,REC.STRUCTURE_NUMBER,REC.M3I_OBJECT_ID,VMAXID+VCOUNT,NULL,NULL);
--RUN THE DELTA FME
END LOOP;


--transaction for dist conn
Insert into TCGACDS.GCM_CONN_TRANSACTION (RECORD_ID,TABLE_NAME,OPERATION,TRANS_DATE,SYNC_DATE,PROCESS_DATE,CIRCUIT_NAME1,CIRCUIT_NAME2,ID,CONNECTIVITY_PROCESSED,SOR) 
SELECT ID,'CIRCUIT_HEAD','UPDATE',SYSTIMESTAMP,SYSTIMESTAMP,SYSTIMESTAMP,CIRCUIT_NAME,NULL,CONN_TRANS_ID_SEQ.NEXTVAL,'N','GESW' 
FROM TCGACDS.CIRCUIT_HEAD WHERE ROWNUM<V_RCNT_CKT;
--ENABLE SBS JOB STATS TO SBS_COMPLETE

--transaction for DERDM
SELECT MAX(BATCH_NO) INTO VMAX_BATCH FROM TCGACDS.GCM_DER_DM_LIST_DELTA;
UPDATE TCGACDS.GCM_DER_DM_LIST_DELTA SET PROCESS_STATUS='PROCESSED',BATCH_NO=VMAX_BATCH+1 WHERE PROCESS_STATUS='GCM_PROCESSED' AND ROWNUM<V_RCNT_DRDM;
--GET MAX BATCH NO FROM TABLE, RUN THE FME TO POPULATE 

commit;
END;