DECLARE
V_GESW_JOB NUMBER;
V_STATS_GE VARCHAR2(200 BYTE);
V_SAP_JOB VARCHAR2(200 BYTE);
BEGIN
        TCGACDS.GCM_PKG_SUB_I_CONN.GCM_P_INIT_DIST_SUB_I_CONN (V_GESW_JOB);
        
        BEGIN
            DELETE FROM TCGACDS.GCM_SUB_I_CONN_SUBSTATIONS WHERE SUBSTATION_ID IS NOT NULL;
        
            INSERT INTO TCGACDS.GCM_SUB_I_CONN_SUBSTATIONS (NAME, MRID, LAST_MODIFIED_DATE, LAST_MODIFIED_TYPE, BANK_TYPE, IN_SERV_DATETIME, SUBSTATION_ID, SUBSTATION_NUMBER, SOR)
            WITH MAX_JOB AS (SELECT MRID, TO_CHAR(MAX(TO_NUMBER(GCM_JOBID))) JOB_ID FROM TCGACDS.GCM_SCIM_SUBSTATION SUB JOIN TCGACDS.GCM_SUB_DIST_JOB_STATUS JOB 
                ON JOB.JOBID= SUB.GCM_JOBID  WHERE GCM_SOR = 'GESW' AND JOB.CURRENT_JOB<>'Y' AND JOB.SUCCESS='Y' GROUP BY MRID)
            SELECT SUB.NAME, SUB.MRID, SYSTIMESTAMP, 'LAST_UPDATED', TYP, TO_DATE (ODS.CHAR_VALUE,'MM/DD/YYYY'), SUB.GCM_SUBSTATION_ID, ID.NAME, 'GESW' FROM TCGACDS.GCM_SCIM_SUBSTATION SUB 
            JOIN MAX_JOB MJ ON MJ.MRID = SUB.MRID AND MJ.JOB_ID = SUB.GCM_JOBID
            JOIN TCGACDS.SUBSTATION GE ON SUB.MRID=GE.M3I_OBJECT_ID
            LEFT JOIN TCGACDS.GCM_SCIM_SUBSTATIONIDENTIFIER ID 
                ON SUB.MRID=ID.SUBSTATIONID AND SUB.GCM_JOBID=ID.GCM_JOBID AND ID.NAMETYPE='SCE_SAP_ID'
            LEFT JOIN (SELECT CHAR_VALUE, TRIM(REGEXP_SUBSTR(FLOC_ID,'[^-]+',1,2)) FLOC, ROW_NUMBER() OVER (PARTITION BY TRIM(REGEXP_SUBSTR(FLOC_ID,'[^-]+',1,2)) ORDER BY TRIM(REGEXP_SUBSTR(FLOC_ID,'[^-]+',1,2))) AS RN FROM TCGACDS.ODS012_FLOC_CHARS WHERE CLASS IN ('ES_SUBS','ED_SUBS','EX_SUBS') AND CHAR_NAME='E_IN_SERVICE_DATE') ODS 
                ON ID.NAME=ODS.FLOC
            WHERE ID.NAME NOT IN (SELECT NVL(SUBSTATION_NUMBER,'NO VALUE') FROM TCGACDS.GCM_SUB_I_CONN_SUBSTATIONS)
            AND SUB.NAME NOT IN (SELECT NAME FROM TCGACDS.GCM_SUB_I_CONN_SUBSTATIONS) AND NVL(RN,1)=1;
            
			COMMIT;
        EXCEPTION WHEN OTHERS THEN
            rollback;
        end;
        
        TCGACDS.GCM_PKG_SUB_I_CONN.GCM_P_SAP_PROCESS_STATUS (V_SAP_JOB);

        IF V_SAP_JOB IS NOT NULL THEN

            --Perform GESW-SAP Enrichment
            TCGACDS.GCM_PKG_SUB_I_CONN.GCM_P_SAP_DIST_LOAD (V_SAP_JOB, V_GESW_JOB, V_STATS_GE);

            --Log stats and update the status of job in SAP Process table
            TCGACDS.GCM_PKG_SUB_I_CONN.GCM_P_SAP_STATS (V_SAP_JOB, '0-0-0-0-0-0-0', V_STATS_GE);
        END IF;
END;